### ISSUE TITLE
TPRINT con PDFPRINT    Grosor de lineas

### ISSUE THREAD

**Issue by jogabar** [oohg/core#127]
Hola:

Al imprimir líneas hay diferencias en como lo hace con HBPRINTER y PDFPRINT, me explico:

Líneas de código para dibujo de líneas con PDFPRINT:
oPrint:printline(200,0,200,205,,0) 		// LINEA HORIZONTAL    No dibuja línea, si en HBPRINTER
oPrint:printline(205,0,205,205,,0.2) 		// LINEA HORIZONTAL    grosor 0,3 mm  aprox.
oPrint:printline(210,0,210,205,,0.5) 		// LINEA HORIZONTAL    grosor 1 mm
oPrint:printline(220,0,220,205,,1) 		// LINEA HORIZONTAL    grosor 2 mm

Líneas de código para dibujo de líneas con HBPRINTER:
oPrint:printline(200,0,200,205,,0) 		// LINEA HORIZONTAL    grosor 0,1 mm  aprox.   Viene por defecto
oPrint:printline(205,0,205,205,,0.2) 		// LINEA HORIZONTAL    grosor 0,1 mm  aprox.
oPrint:printline(210,0,210,205,,0.5) 		// LINEA HORIZONTAL    grosor 0,2 mm  aprox
oPrint:printline(220,0,220,205,,1) 		// LINEA HORIZONTAL    grosor 0,5 mm  aprox

**Comment by fyurisich** [comment]
Por favor adjunta un ejemplo mínimo compilable que permita reproducir el problema.
Gracias

**Comment by fyurisich** [comment]
Fixed. See 58e92ad
