### ISSUE TITLE
TPRINT con PDFPRINT    usando font tamaño 10 y 9 en misma linea

### ISSUE THREAD

**Issue by jogabar** [oohg/core#128]
Hola:
Al usar TPRINT con HBPRINTER, mezclando fonts de tamaño 10 y 9 el siguiente código imprime bien:
oPrint:printdata(nLin, 75, "Totales ---->",,10,.t.)
oPrint:printdata(nLin,105, TRANSFORM( nG_SaldoFac, "@E@Z 999,999,999,999" ),,9,.t.)
oPrint:printdata(nLin,135, TRANSFORM( nG_SaldoNC, "@E@Z 999,999,999,999" ),,9,.t.)
oPrint:printdata(nLin,165, TRANSFORM( nG_SaldoFac - nG_SaldoNC, "@E@Z 999,999,999,999" ),,9,.t.)

En TPRINT el mismo código lo hace bien. Subí imagen.

![Diferencia al imprimir distintos tamaño de fonts en PDFPRINT](https://user-images.githubusercontent.com/41596024/54761411-d0ceb800-4bd0-11e9-96a4-8b9a3400c058.jpg)

**Comment by fyurisich** [comment]
Por favor adjunta un ejemplo mínimo compilable que permita reproducir el problema.
Gracias

**Comment by fyurisich** [comment]
Closed without action because I wasn't able to reproduce the problem and the because the user didn't provide a test sample.
