### ISSUE TITLE
TPRINT

### ISSUE THREAD

**Issue by lu4376** [oohg/core#130]
**Describe the bug**

**Screenshots**

**Error logs**
If applicable, add a copy of ErrorLog.htm and/or hb_out.log files.

**To Reproduce**
Add a PRG file (minimal, self-contained and compilable) that reproduces the bug.
Detail the steps to build, execute and reproduce the bug.

**Expected behavior**

**Additional information**
Add any additional information about the problem here.

**Comment by fyurisich** [comment]
Not enough information to proceed.
