### ISSUE TITLE
Luego de Tprint.. Bloqueo del programa

### ISSUE THREAD

**Issue by joseforozco** [oohg/core#131]
**Describe the bug**
El programa se "bloquea" o no puedo retomar el focus.. luego de imprimir

**Screenshots**
no aplica

**Error logs**
no genera

**To Reproduce**
FUNCTION Imprimir_remision()

   LOCAL Destino
   LOCAL xxy := 0
   LOCAL Rutica := hb_CurDrive() + ":" + Dirname() + "\"
   LOCAL yy := 0

   Destino = Upper( "MINIRINT" )
   Impresion := Tprint( Destino )
   impreso++

   WITH OBJECT Impresion
      :Init()
      :Selprinter( .F., .F., .F.,,, )
      :Setunits( "MM", )
   END WITH
   IF Impresion:Lprerror
      Impresion:release()
      RETURN
   ENDIF

**Expected behavior**

**Additional information**

**Comment by fyurisich** [comment]
Fixed. See b2a59c8

**Comment by fyurisich** [comment]
Subí a GitHub el arreglo para este problema.

Saludos
Fernando Yurisich
