### ISSUE TITLE
TPrint  error ENDDOC cuando Preview es .F.

### ISSUE THREAD

**Issue by jogabar** [oohg/core#132]
**Describe the bug**
Cuando se llama a TPrint sin Preview da error en la linea 425 del winprint.prg

**Screenshots**
No applicable.

**Error logs**
Aplicación: C:\Contabil\Contabil.exe
Fecha: 25.04.19 Hora: 11:08:21
Versión: OOHG Ver. 2019.02.27
Alias en uso: MOVDOCTO
Nombre de Equipo: DEVELOPER2
Nombre de Usuario: DEVELOPER2
Error: Error BASE/1132 Error de rango: acceso al array
Llamada desde HBPRINTER:ENDDOC (425) in winprint.prg
Llamada desde THBPRINTER:ENDDOCX (2168) in h_print.prg
Llamada desde THBPRINTER:ENDDOC (548) in h_print.prg
Llamada desde IMPRIMEVOU (339) in C:\OOHG_D~1\CONTAB~1\CON_DO~1\X\IMPVOUCH.PRG
Llamada desde IMPRIMIRVOUCHER (94) in C:\OOHG_D~1\CONTAB~1\CON_DO~1\X\ConsultaVoucher.PRG
Llamada desde (b)CONSULTA_VOUCHER (45) in C:\OOHG_D~1\CONTAB~1\CON_DO~1\X\ConsultaVoucher.PRG
Llamada desde (b)EVAL (0)
Llamada desde _OOHG_EVAL_ARRAY (0)
Llamada desde TBUTTON:DOEVENT (1909) in h_controlmisc.prg
Llamada desde TBUTTON:DOEVENTMOUSECOORDS (1925) in h_controlmisc.prg
Llamada desde TBUTTON:EVENTS_COMMAND (2193) in h_controlmisc.prg
Llamada desde TWINDOW:EVENTS (0) in h_windows.prg
Llamada desde _OOHG_TFORM_EVENTS2 (1743) in h_form.prg
Llamada desde TFORMMODAL:EVENTS (0) in h_form.prg
Llamada desde _OOHG_DOMESSAGELOOP (0)
Llamada desde TFORMMODAL:MESSAGELOOP (647) in h_form.prg
Llamada desde _ACTIVATEWINDOW (2783) in h_form.prg
Llamada desde CONSULTA_VOUCHER (57) in C:\OOHG_D~1\CONTAB~1\CON_DO~1\X\ConsultaVoucher.PRG
Llamada desde MSUP_CON (285) in C:\OOHG_D~1\CONTAB~1\CON_DO~1\X\MSUP_CON.PRG
Llamada desde MAIN (102) in C:\OOHG_D~1\CONTAB~1\CON_DO~1\X\MENU.PRG

**To Reproduce**
Add a PRG file (minimal, self-contained and compilable) that reproduces the bug.
Detail the steps to build, execute and reproduce the bug.

**Expected behavior**

**Additional information**
El lWait queda en .T. aún cuando el ::PreviewMode está en .F.

METHOD EndDoc( cParent, lWait, lSize ) CLASS HBPrinter

   ASSIGN lWait VALUE lWait TYPE "L" DEFAULT ::PreviewMode
   ASSIGN lSize VALUE lSize TYPE "L" DEFAULT ! lWait

   IF ::PreviewMode
      ::Preview( cParent, lWait, lSize )
   ELSE
      IF lWait
          // MsgInfo( ::aopisy[ 31 ], "" )  linea original
         // Si no es con preview es impresión directa y no debe mostrar este mensaje
         MsgInfo( "Haga clic en OK para continuar.", "" )
      ENDIF
      RR_ENDDOC( ::hData )
   ENDIF
   ::Printing := .F.
RETURN Self

**Comment by fyurisich** [comment]
Fixed. See 1929ea1

**Comment by fyurisich** [comment]
Acabo de subir el arreglo a GitHub.
Disculpa la demora.
Fernando
