### ISSUE TITLE
Error al imprimir...oPrint:enddoc()

### ISSUE THREAD

**Issue by ViCagCan** [oohg/core#133]
Buenas tardes:

   Me están informando de que al realizar un listado hay veces que les aparece en pantalla un error y se cierra la aplicación. 

   La línea donde da el error es siempre la misma, es la que contiene la orden  oPrint:enddoc() la cual aparece en múltiples listados como es lógico y el error se produce en diferentes listados y siempre en la línea que contiene dicha instrucción.

   oprint en un principio lo tenía declarado como LOCAL en cada uno de los diferentes listados pero también he probado a cambiarlo a PUBLIC y sigue dando el mismo error.

   La forma de cargar dicha "variable" es de la siguiente forma... 

oPrint:=tprint(cTipoDocImprimir) 
oPrint:init()

   En la primera línea se le pasa como parámetro miniprint o hbprinter(por lo general este último) a partir de ahí se realizan los diferentes apartados de la impresión: cabecera, texto y cuando se detecta que hemos llegado al final de la hoja se envía las ordenes...

oPrint:endpage()
oPrint:beginpage()

   Y si es el final del documento... oPrint:enddoc() que es donde da el error. Paso a copiar un log "tipo" que muestra este error...

Aplicación: C:\GesTaller\GesTaller.EXE
Fecha: 04/07/2019 Hora: 12:01:44
Versión: OOHG Ver. 2017.08.25
Alias en uso:
Nombre de Equipo: I5-PC
Nombre de Usuario: I5-PC
Error: Non top modal window *_MODALHIDE* can't be released. Program terminated.
Llamada desde TFORMMODAL:RELEASE (2052) in h_form.prg
Llamada desde THBPRINTER:ENDDOC (513) in h_print.prg
Llamada desde **LISFAC (931)** in E:\PROYEC~1\GESTAL~1\Otras\LisGen.PRG
Llamada desde (b)LISGEN (34) in E:\PROYEC~1\GESTAL~1\Otras\LisGen.PRG
Llamada desde (b)EVAL (0)
Llamada desde _OOHG_EVAL_ARRAY (0)
Llamada desde TBUTTON:DOEVENT (1775) in h_controlmisc.prg
Llamada desde TBUTTON:DOEVENTMOUSECOORDS (1791) in h_controlmisc.prg
Llamada desde TBUTTON:EVENTS_COMMAND (2125) in h_controlmisc.prg
Llamada desde TWINDOW:EVENTS (0) in h_windows.prg
Llamada desde _OOHG_TFORM_EVENTS2 (1670) in h_form.prg
Llamada desde TFORMMODAL:EVENTS (0) in h_form.prg
Llamada desde _OOHG_DOMESSAGELOOP (0)
Llamada desde TFORMMODAL:MESSAGELOOP (636) in h_form.prg
Llamada desde _ACTIVATEWINDOW (2683) in h_form.prg
Llamada desde LISGEN (38) in E:\PROYEC~1\GESTAL~1\Otras\LisGen.PRG
Llamada desde (b)FACTURASTOOLBAR (1532) in E:\PROYEC~1\GESTAL~1\DOCUME~1\Facturas.prg
Llamada desde (b)EVAL (0)
Llamada desde _OOHG_EVAL_ARRAY (0)
Llamada desde TTOOLBUTTON:DOEVENT (1775) in h_controlmisc.prg
Llamada desde TTOOLBUTTON:DOEVENTMOUSECOORDS (1791) in h_controlmisc.prg
Llamada desde TTOOLBAR:EVENTS_COMMAND (329) in h_toolbar.prg
Llamada desde TWINDOW:EVENTS (0) in h_windows.prg
Llamada desde TSPLITBOX:EVENTS (0) in h_controlmisc.prg
Llamada desde _OOHG_DOMESSAGELOOP (0)
Llamada desde TFORM:MESSAGELOOP (636) in h_form.prg
Llamada desde _ACTIVATEWINDOW (2683) in h_form.prg
Llamada desde FACTURAS (114) in E:\PROYEC~1\GESTAL~1\DOCUME~1\Facturas.prg
Llamada desde (b)INICIOTOOLBAR (769) in E:\PROYEC~1\GESTAL~1\Inicio.PRG
Llamada desde (b)EVAL (0)
Llamada desde _OOHG_EVAL_ARRAY (0)
Llamada desde TTOOLBUTTON:DOEVENT (1775) in h_controlmisc.prg
Llamada desde TTOOLBUTTON:DOEVENTMOUSECOORDS (1791) in h_controlmisc.prg
Llamada desde TTOOLBAR:EVENTS_COMMAND (329) in h_toolbar.prg
Llamada desde TWINDOW:EVENTS (0) in h_windows.prg
Llamada desde TSPLITBOX:EVENTS (0) in h_controlmisc.prg
Llamada desde _OOHG_DOMESSAGELOOP (0)
Llamada desde TFORMMAIN:MESSAGELOOP (636) in h_form.prg
Llamada desde _ACTIVATEWINDOW (2683) in h_form.prg
Llamada desde MAIN (458) in E:\PROYEC~1\GESTAL~1\Inicio.PRG

   Donde está en negrita corresponde a la orden oPrint:enddoc()  no hay ninguna orden más en dicha línea.

   He intentado reproducir el error pero no lo he conseguido, es algo que no sólo le pasa a un usuario y es aleatorio. Hoy sin ir más lejos de 6 log de error que he recibido... 5 es causado por este "problema".

   Si consigo más información que pueda aclarar este tema lo iré añadiendo.

   Un saludo.

**Comment by fyurisich** [comment]
Fixed. See b2a59c8

**Comment by fyurisich** [comment]
Subí a GitHub el arreglo para este problema.

Saludos
Fernando Yurisich
