### ISSUE TITLE
Miniprint "ok" print button on preview not work

### ISSUE THREAD

**Issue by brawnius** [oohg/core#139]
**Describe the bug**
when you push button print and preview appears , yoou need to push printer button
then a dialog appears an you need to push the ok button to finally print 
and that not work 

![miniprint](https://user-images.githubusercontent.com/53201327/61675984-adc42a00-acd0-11e9-8950-7e8af59bd42d.png)

[pruebaoohg.zip](https://github.com/oohg/core/files/3419743/pruebaoohg.zip)

**Comment by fyurisich** [comment]
Fixed. See a5a57a5
