### ISSUE TITLE
ventana minimizada no vuelve a estar en el foco principal al pulsar boton de nuevo

### ISSUE THREAD

**Issue by jimeneztatodavid** [oohg/core#167]
Fernando, tengo una ventana principal con dos botones, al pulsar un botón se abre una nueva ventana y al pulsar el otro botón se abre otra ventana que se superpone encima de la anterior cogiendo el foco.

Antes de la actualización de la semana pasada, si pulsaba el botón de la primera ventana, esta volvía a estar delante de todas las ventanas con el foco en ella. Ahora por mucho que pulse el botón esto no ocurre.

#include "oohg.ch"

FUNCTION Main

   
   DEFINE WINDOW Form_1 OBJ oForm ;
      AT 0,0 ;
      WIDTH 640 ;
      HEIGHT 480 ;
      TITLE 'PRUEBA' ;
      MAIN 

     DEFINE TOOLBAR ToolBar_1 FLAT BUTTONSIZE 155,30 RIGHTTEXT BORDER BOLD 
      BUTTON Boton001 CAPTION "Clientes"          ACTION { || clientes() } SEPARATOR
      BUTTON Boton002 CAPTION "Proveedores"       ACTION { || proveedores() } SEPARATOR
     END TOOLBAR

      ON KEY ESCAPE ACTION Form_1.Release()
   END WINDOW

   CENTER WINDOW Form_1
   ACTIVATE WINDOW Form_1

RETURN NIL

STATIC FUNCTION CLIENTES()
    if IsWindowDefined(wndclientes) = .T.
		declare window wndclientes
		wndclientes.restore
		wndclientes.show
		wndclientes.setfocus
		return 
	endif
	
	define window wndclientes;
		at 10,10;
		width 1010 ;
        height 600;
        BACKCOLOR  {179,217,255}                    ;
		title 'Clientes' 

        ON KEY ESCAPE ACTION wndclientes.release()
    END WINDOW

   CENTER WINDOW wndclientes
   ACTIVATE WINDOW wndclientes
RETURN(NIL)

STATIC FUNCTION PROVEEDORES()
    if IsWindowDefined(wndproveedores) = .T.
		declare window wndproveedores
		wndproveedores.restore
		wndproveedores.show
		wndproveedores.setfocus
		return 
	endif
	
	define window wndproveedores;
		at 10,10;
		width 1010 ;
        height 600;
        BACKCOLOR  {179,255,255}                    ;
		title 'Proveedores' 

        ON KEY ESCAPE ACTION wndproveedores.release()
    END WINDOW

   CENTER WINDOW wndproveedores
   ACTIVATE WINDOW wndproveedores
RETURN(NIL)

**Comment by fyurisich** [comment]
¿Podrías precisar la fecha en que funcionaba correctamente?
Me ha sido imposible encontrar un punto en el tiempo en que el .prg que enviaste se comporta como dices.
Gracias

**Comment by fyurisich** [comment]
Con la última distro publicada en sourceforge sucede lo mismo.

**Comment by jimeneztatodavid** [comment]
Tengo otra aplicación que no he compilado aun con la ultima distro publicada y funciona bien.

 

La última compilación de esta aplicación es del 31 de Julio de este año.

 

Por si te sirve de ayuda

 

Saludos.

 

De: Fernando Yurisich <notifications@github.com> 
Enviado el: martes, 24 de septiembre de 2019 23:53
Para: oohg/core <core@noreply.github.com>
CC: jimeneztatodavid <jimeneztatodavid@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [oohg/core] ventana minimizada no vuelve a estar en el foco principal al pulsar boton de nuevo (#167)

 

¿Podrías precisar la fecha en que funcionaba correctamente?
Me ha sido imposible encontrar un punto en el tiempo en que el .prg que enviaste se comporta como dices.
Gracias

**Comment by fyurisich** [comment]
Para que funcione como quieres deberías agregar la cláusula NOWAIT a los ACTIVATE de las ventanas hijas.
Para poder seguir investigando necesito que me pases la versión vieja de OOHG con la cual este programa funcionaba. Gracias

**Comment by jimeneztatodavid** [comment]
Hola, que necesitas que te pase exactamente:

*	El core completo
*	El archivo changelog

 

Saludos

 

De: Fernando Yurisich <notifications@github.com> 
Enviado el: jueves, 26 de septiembre de 2019 1:46
Para: oohg/core <core@noreply.github.com>
CC: jimeneztatodavid <jimeneztatodavid@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [oohg/core] ventana minimizada no vuelve a estar en el foco principal al pulsar boton de nuevo (#167)

 

Para que funcione como quieres deberías agregar la cláusula NOWAIT a los ACTIVATE de las ventanas hijas.
Para poder seguir investigando necesito que me pases la versión vieja de OOHG con la cual este programa funcionaba. Gracias

**Comment by fyurisich** [comment]
Envíame ambas.
Gracias

**Comment by fyurisich** [comment]
Acabo de bajar la distro y compilar el ejemplo.
No pude replicar el comportamiento esperado.
Funciona igual que la versión actual.
Saludos

**Comment by jimeneztatodavid** [comment]
Pues me quedo a cuadros, con esa versión si compilo mi programa el comportamiento de las ventanas es el mismo pero sin aplicarle al Active la clausula NOWAIT que me indicaste.

 

Gracias.

 

De: Fernando Yurisich <notifications@github.com> 
Enviado el: sábado, 28 de septiembre de 2019 3:39
Para: oohg/core <core@noreply.github.com>
CC: jimeneztatodavid <jimeneztatodavid@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [oohg/core] ventana minimizada no vuelve a estar en el foco principal al pulsar boton de nuevo (#167)

 

Acabo de bajar la distro y compilar el ejemplo.
No pude replicar el comportamiento esperado.
Funciona igual que la versión actual.
Saludos

**Comment by fyurisich** [comment]
Cuándo dices mi programa, ¿te refieres al código que me enviaste para
probar o a otro?
Porque si es otro, tal vez haya algo que esté ocasionando la diferencia de
comportamiento.

**Comment by jimeneztatodavid** [comment]
Es otro programa, pero el ejemplo enviado está realizado con las mismas
instrucciones de botones y ventanas.

La única diferencia es que mi programa está compilado con QPM

Saludos

**Comment by fyurisich** [comment]
Por favor envíame el .QPM para hacer pruebas.
Gracias

**Comment by fyurisich** [comment]
¿En tus programas utilizas _OOHG_NestedSameEvent(  .T. )?

**Comment by jimeneztatodavid** [comment]
Hola, si.

 

De: Fernando Yurisich <notifications@github.com> 
Enviado el: martes, 8 de octubre de 2019 0:58
Para: oohg/core <core@noreply.github.com>
CC: jimeneztatodavid <jimeneztatodavid@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [oohg/core] ventana minimizada no vuelve a estar en el foco principal al pulsar boton de nuevo (#167)

 

¿En tus programas utilizas _OOHG_NestedSameEvent( .T. )?

**Comment by fyurisich** [comment]
Ah, con razón no encontraba el problema.
El ejemplo que me enviaste no lo tiene y por eso no podía reproducir el error.
Por favor actualiza desde GitHub y vuelve a probar.

**Comment by jimeneztatodavid** [comment]
Es verdad, disculpa.

 

He probado y con la actualización desde github y quitando la clausula NOWAIT vuelve a funcionar como antes

 

Gracias.

 

De: Fernando Yurisich <notifications@github.com> 
Enviado el: martes, 8 de octubre de 2019 13:31
Para: oohg/core <core@noreply.github.com>
CC: jimeneztatodavid <jimeneztatodavid@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [oohg/core] ventana minimizada no vuelve a estar en el foco principal al pulsar boton de nuevo (#167)

 

Ah, con razón no encontraba el problema.
El ejemplo que me enviaste no lo tiene y por eso no podía reproducir el error.
Por favor actualiza desde GitHub y vuelve a probar.

**Comment by fyurisich** [comment]
Function _OOHG_NestedSameEvent is not working properly.
Fixed. See d164df3de6b4876d9f8c45346d6144deb356c347
