### ISSUE TITLE
FALLO EN IMPRESION PDF DE GRAFICO EN VENTANA

### ISSUE THREAD

**Issue by jimeneztatodavid** [oohg/core#168]
Hola, tengo en mi aplicación una ventana donde se muestra un grafico de barras. En dicha ventana tengo un botón que al pulsarlo se creaba directamente un documento pdf con el contenido de la ventana para poderlo imprimir directamente.

Ahora al pulsar el botón de imprimir dentro de la ventana del grafico, se abre correctamente el adobe acrobat reader pero el documento sale en blanco y ventana con mensaje "Ha habido un error al leer la secuencia"

![image](https://user-images.githubusercontent.com/55757463/65568016-93206280-df58-11e9-8860-c3d242e9c3a4.png)

#include "oohg.ch"

FUNCTION Main

   LOCAL oWnd, oRch
   
    _OOHG_printlibrary:="PDFPRINT"

   DEFINE WINDOW Win_1 OBJ oWnd ;
      AT 0,0 ;
      WIDTH 600 ;
      HEIGHT 400 ;
      TITLE 'Prueba impresion de ventana'

      ON KEY ESCAPE ACTION oWnd:Release()
    
	 DEFINE TOOLBAR ToolBar_1 FLAT BUTTONSIZE 155,30 RIGHTTEXT BORDER BOLD 
      BUTTON Boton001 CAPTION "Grafico"          ACTION { || ventanagrafico() } SEPARATOR
     END TOOLBAR
      

   END WINDOW

   ownd:Center()
   ownd:Activate()

RETURN NIL

static function ventanagrafico()
   local enero:=10
   local febrero:=20
   local marzo:=30
   local abril:=40
   local mayo:=50
   local junio:=60
   local julio:=70
   local agosto:=80
   local septiembre:=90
   local octubre:=100
   local noviembre:=110
   local diciembre:=120
  
      
    
   if IsWindowDefined(GraphTestfactura) = .T.
    	declare window GraphTestfactura 
		GraphTestfactura.restore
      GraphTestfactura.show
		GraphTestfactura.setfocus
		return 
	endif

    DEFINE WINDOW GraphTestfactura obj owingra ;
      AT 0,0 ;
      WIDTH 860 ;
      HEIGHT 600 ;
      NOMAXIMIZE ;
      BACKCOLOR  {179,217,255}                    ;
      TITLE "Facturación" 
      
      @ 10,120 IMAGE Image_1 obj oImage PICTURE "graficoestadistica.BMP" HEIGHT 40 WIDTH 40 
	  
	  DrawBarGraph ( enero , febrero , marzo , abril , mayo , junio , julio , agosto , septiembre , octubre, noviembre , diciembre  )
    
	  
	  @ 500,550 BUTTON Button_1 CAPTION "Imprimir"  ACTION oWingra:Print( 1, 1, 40, 80, .F., "JPG", 100 )
      
    END WINDOW
   
    GRAPHTESTfactura.BUTTON_1.SETFOCUS
   
    GraphTestfactura.Center
   
    ACTIVATE WINDOW GraphTestfactura  
return(nil)

static function DrawBarGraph ( enero , febrero , marzo , abril , mayo , junio , julio , agosto , septiembre , octubre, noviembre , diciembre )
   local  arraymes:={ {enero} , {febrero} , {marzo} , {abril} , {mayo} , {junio} , {julio} , {agosto} , {septiembre} ,;
                         {octubre} , {noviembre} , {diciembre} }        

    
  
   DRAW GRAPH                      ;
   IN WINDOW GraphTestfactura             ;
   AT 10,10                        ;
   TO 550,550                      ;
   TITLE "Facturacion / Meses Año "       ;
   TYPE BARS                       ;
   SERIES arraymes                     ;
   YVALUES {"2019"}                     ;  
   DEPTH 15                        ;
   BARWIDTH 15                     ;
   HVALUES 15                      ;
   SERIENAMES {"Ene:","Feb:","Mar:","Abr:","May:","Jun:","Jul:","Ago:","Sep:","Oct:","Nov:","Dic:"}         ;
   COLORS {{255,0,0},{0,0,255},{128,128,255},{0,255,0},{255,128,64},{128,0,128},{255,0,255},{128,128,255},{128,0,0},;
            {128,128,128},{255,0,128},{128,255,255} }                ;
   3DVIEW                          ;
   SHOWGRID                        ;
   SHOWXVALUES                     ;
   SHOWYVALUES                     ;
   SHOWLEGENDS                     ;
   NOBORDER  
return(nil)

**Comment by fyurisich** [comment]
Fixed. See 20b9cb78ab9ea34a59905064694ac54ab87ec505
