### ISSUE TITLE
Division by zero at method Preview of HBPRINTER

### ISSUE THREAD

**Issue by ViCagCan** [oohg/core#169]
Buenas noches:

He bajado los fuentes y creado las librerías sin problemas al igual que he compilado una aplicación mía sin dar problemas.

Al realizar pruebas de impresión me encuentro con el siguiente problema:

*.- Imprime la hoja sin problemas hasta que llega a una instrucción EndDoc. En ese momento nos muestra un error en pantalla con la siguiente información...

Error: Error BASE/1132 Error de rango: acceso al array
Llamada desde HBPRINTER:ENDDOC (425) in winprint.prg
Llamada desde THBPRINTER:ENDDOCX (2168) in h_print.prg
Llamada desde THBPRINTER:ENDDOC (548) in h_print.prg
Llamada desde LISFAC (926)

1.- En la línea 926 de LisFac.prg aparece la siguiente instrucción: oPrint:EndDoc()
2.- oPrint es el objeto asignado de la siguiente forma: oPrint:=Tprint(cTipoDocImprimir)

No se ha cambiado nada de la rutina de impresión, sólo se ha creado la lib y vuelta a compilar todo el proyecto desde cero.

He revisado WinPrint y  h_print pero no consigo ver donde puede estar el error ya sea de los fuentes o de mi rutina de impresión.

Un saludo.

**Comment by fyurisich** [comment]
Por favor adjunta un pequeño programa compilable que muestre el error al ejecutarse.
Gracias
Fernando

**Comment by fyurisich** [comment]
Se cierra dado a) el tiempo transcurrido sin respuesta y b) que no se pudo reproducir el error.

**Comment by ViCagCan** [comment]
Buenas tardes Fernando:

Disculpa pero he andado de viaje por trabajo y he estado un poco liado.

Revisando el error me he dado cuenta que el problema lo tengo al añadir el archivo propio de control de errores, es decir, si no utilizo la rutina propia de errores, imprime sin problemas pero si añado dicha rutina da el error.

Por mucho que he mirado... no consigo ver donde puede estar el error. Te envío un zip con un ejemplo realizado con uno de tus ejemplos, para ser exacto el S002.prg. Al ejemplo lo único que le he añadido es q utilice la rutina de errores que tenía descargada de "algún lado" hace tiempo.

Un saludo.
[Error.zip](https://github.com/oohg/core/files/3730444/Error.zip)

**Comment by fyurisich** [comment]
El error se produce porque en el método PrevShow de HBPrinter hay una división por cero.
En OOHG las divisiones por cero, al igual que en Harbour y Clipper, en lugar de cancelar retornan 0.
Tu rutina de errores cancela porque así la diseñaste.

**Comment by fyurisich** [comment]
Fixed. See b704296ac8c530d7de2a940f8d3fdf552f4cf02d
