### ISSUE TITLE
Activar/Desactivar xBrowse

### ISSUE THREAD

**Issue by ViCagCan** [oohg/core#171]
Buenas tardes:

Si se define el control Xbrowse con sus correspondientes acciones por ejemplo en ON CHANGE, como Falso de la siguiente forma:

WnFiscal.xBrowse_1.Enabled    := !lPasoFiscal

Donde lPasoFical es un parámetro pasado a la función donde lo único que se hace es pasarle un .T. o un .F.

Cuando a la función le paso un .F. desactivo un control ToolBoard y el xBrowse a la vez que se activan otra serie de controles.

En ese momento, cuando debería estar ya en .F. si me pongo sobre el control y me muevo ya sea con el ratón o las flechas... la orden que hay cargada en ON CHANGE sigue siendo activa y funcional cuando entiendo que no debería ser así.

Te adjunto un pequeño video en el que se ve como funciona y como al dar de alta un nuevo concepto... funciona "mal"

La rutina que se encarga de activar o desactivar los controles de la ventana es la siguiente:

// ---------------------------------------------------------------------------------------------------------------------------------------------------
FUNCTION MuestraControlesFiscal(lPasoFiscal)
// ---------------------------------------------------------------------------------------------------------------------------------------------------
WnFiscal.Text_2.Enabled       := lPasoFiscal

WnFiscal.picbutt_3.Enabled    := lPasoFiscal
WnFiscal.picbutt_4.Enabled    := lPasoFiscal

WnFiscal.ToolBar_1.Enabled    := !lPasoFiscal

IF lPasoFiscal
   WnFiscal.Text_2.SetFocus
ELSE
   oWnFiscal:SetFocus()
ENDIF   

RETURN

Un saludo.

[error.zip](https://github.com/oohg/core/files/3751954/error.zip)

**Comment by ViCagCan** [comment]
Se me olvidó poner como está definido el  xBrowse dentro del FMG..

   @ 80, 10 XBROWSE xbrowse_1 ;
      OBJ oFiscal ;
      WIDTH 287 ;
      HEIGHT 250 ;
      HEADERS {'IDENTIFICACION FISCAL'} ;
      WIDTHS {265} ;
      WORKAREA (obaseFiscal) ;
      FIELDS {{|o| o:Fieldget(1)}} ;
      FONT 'Arial' ;
      SIZE 10 ;
      DYNAMICBACKCOLOR { fColor } ;
      ON CHANGE ActualizarFiscal() ;
      FONTCOLOR BLACK

Lo que se ve funcionando en el video en la función ActualizarFiscal()

**Comment by fyurisich** [comment]
Por favor agrega un ejemplo mínimo compilable para hacer pruebas.
Gracias

**Comment by ViCagCan** [comment]
Buenas tardes:

Aunque yo estoy utilizando un xBrowse para cargar los datos de una tabla MySql... he estado mirado uno de los ejemplos que hay en Git con un Browse y funciona igual que en el xBrowse. Parece como que se desactiva(desaparece hasta el color de la línea en la cual estás posicionado) pero si te fijas en la línea que escribe abajo... el contador va subiendo o bajando según te mueves por el browse que es algo que se lanza en el ON CHANGE.

En la línea 85 he puesto esta instrucción    Form_1.Browse_1.Enabled := .F. que es la única modificación a tu ejemplo.

Espero que te sirva de ayuda. Un saludo.


[Error.zip](https://github.com/oohg/core/files/3752197/Error.zip)

**Comment by fyurisich** [comment]
Fixed. See 4ee6e49bffd40c8717c7a09fd4813c29f9fc80bd
