### ISSUE TITLE
Ventana Main desaparece de atras al editar un browse en una ventana Modal

### ISSUE THREAD

**Issue by jimeneztatodavid** [oohg/core#183]
Al editar un campo dentro de un browse, la ventana MAIN desaparece de atrás cuando hay otro programa Windows abierto a la vez con nuestro programa

**Comment by fyurisich** [comment]
Actualiza desde Github. Días pasados subí el arreglo.
Saludos
Fernando Yurisich

**Comment by fyurisich** [comment]
@jimeneztatodavid said

Adjunto fichero comprimido RAR con prg y dbf necesario para prueba.
Para ver lo que sucede, abre cualquier programa en windows, ahora abre el programa que te adjunto, entra en el browse y edita el campo Nº Pedido Cliente.
Al pulsar el enter al haber editado este campo del browse, la ventana MAIN desaparece y detrás del browse aparece la ventana del programa windows que abriste primero.

**Comment by fyurisich** [comment]
Fixed. See ac718c9403013048b98db7946febfae1131e75e2
