### ISSUE TITLE
 Deletecolumn() de Grid/Browse/xBrowse no está funcionando como antes

### ISSUE THREAD

**Issue by CITRO1965** [oohg/core#186]
#include "oohg.ch"
#include "adordd.ch"
#include "Hbclass.ch"

#xcommand TRY  => BEGIN SEQUENCE WITH {| oErr | Break( oErr ) }
#xcommand CATCH [<!oErr!>] => RECOVER [USING <oErr>] <-oErr->
#xcommand FINALLY => ALWAYS

/***/
Function Main()

local n,oC

public cHostName:="NTServer"

private oRsBrw,xbuscar,aHeaders,aFields,aWidths,aCtrl,aJusti

aHeaders:={'Cliente','Razón Social'}
aFields :={}
aWidths :={100,350}
aCtrl   :={ {'TEXTBOX', 'STRING','!!!!!!'}, {'TEXTBOX', 'CHARACTER'} } 
aJusti  :={ GRID_JTFY_LEFT,GRID_JTFY_LEFT }
oC      := Conectar()

CrearTabla( oC )
AgregaRegistros( oC )

cSql:="SELECT cliente,nombre FROM clientes1 ORDER BY cliente"

If !Hb_IsObject(oC)
  MsgStop("Es necesario realizar primeramente la conexion","Error")
  Return
Endif

TRY
  oRsBrw := DBADO():New(cSql, oC)
Catch
  MsgStop(cSql, "Error Comando SQL, Comprobantes en pantalla")
  Return
End Sequence

if !oRsBrw:oRs:Eof()
  For n := 1 TO oRsBrw:oRs:Fields:Count()
    AADD(aFields, &("{|wa| wa:oRs:Fields("+STR(n-1)+"):Value }"))
  Next n
end if

DEFINE WINDOW frmCliente ;
  OBJ ofrmCliente ;
  AT 0, 0 ;
  WIDTH 550 ;
  HEIGHT 400 ;
  TITLE 'Consulta de Clientes' ;
  MAIN
  
  @ 20,10 XBROWSE TbCliente ;
    OBJ oBrwCliente ;
  	WIDTH ofrmCliente:ClientWidth - 40 ;
  	HEIGHT ofrmCliente:ClientHeight - 105 ;
  	WORKAREA ( oRsBrw  ) ;	
  	HEADERS aHeaders ;
  	FIELDS aFields ;
  	WIDTHS aWidths ; 
  	COLUMNCONTROLS aCtrl ;
  	JUSTIFY aJusti ; 
  	FIXEDBLOCKS ;
	NAVIGATEBYCELL

    @ ofrmCliente:ClientHeight - 64, ofrmCliente:ClientWidth - 120 BUTTON btnAceptar ;
         CAPTION "Aceptar" ;
         WIDTH 100 ;
         HEIGHT 24 ; 		 
		 ACTION ( Seleccionar( oGrd,nColu ) )

    @ ofrmCliente:ClientHeight - 64, ofrmCliente:ClientWidth - 230 BUTTON btnCancelar ;
         CAPTION "Salir" ;
         WIDTH 100 ;
         HEIGHT 24 ;
         ACTION ThisWindow.release()
		 
    DEFINE LABEL lblBuscar
  	  ROW ofrmCliente:ClientHeight - 30
  	  COL 10
  	  VALUE "Buscar" 
  	  WIDTH 40 
  	END LABEL
  	
    DEFINE TEXTBOX TxtBuscar
  	  ROW ofrmCliente:ClientHeight - 30
  	  COL 60
  	  WIDTH 250 
  	  VALUE xbuscar
  	  INPUTMASK replicate( "X",50 ) 
      TOOLTIP "Tipee la Razón Social del cliente a buscar"
	  AUTOSKIP .T.
	  ON CHANGE BuscaEnGrid( oC )
    END TEXTBOX

    ON KEY ESCAPE ACTION ofrmCliente:Release()
	  
END WINDOW

ofrmCliente:Center()
ofrmCliente:Activate()

retu

/***/
static Function InitVars( oC )

local cSql

xbuscar:=space(50)
frmCliente.txtBuscar.value:=xbuscar

retu

/***/
static Function BuscaEnGrid( oC )

local cSql,n

xbuscar:=alltrim( frmCliente.txtBuscar.value )

cSql:="SELECT cliente,nombre FROM clientes1 WHERE nombre LIKE '" +xbuscar +"%' ORDER BY cliente"

Do while oBrwCliente:ColumnCount() > 0
  oBrwCliente:DeleteColumn()
end whil
oBrwCliente:deleteallitems()

TRY
  oRsBrw := DBADO():New(cSql,oC)
Catch
  MsgStop(cQuery, "Error Comando SQL")
  Return
End Sequence

if !oRsBrw:oRs:Eof()
  oBrwCliente:WorkArea:= oRsBrw
  aFields:={}
  for n:=1 to oRsBrw:oRs:Fields:Count()
    oBrwCliente:AddColumn( n, &("{|wa| wa:oRs:Fields("+STR(n-1)+"):Value }"),aHeaders[n],aWidths[n],aJusti[n],,,,aCtrl[n] )
  end for
  oBrwCliente:refresh()
  /*
  For n := 1 TO oRsBrw:oRs:Fields:Count()
    AADD(aFields, &("{|wa| wa:oRs:Fields("+STR(n-1)+"):Value }"))
  Next n
  oBrwCliente:refresh()
  */
end if

retu

/***/
static Function Seleccionar( oGrd,nColu )

oGrd:cell(oGrd:value[1],nColu-1,oBrwCliente:cell(oBrwCliente:value[1],1))
ofrmCliente:release()

retu

/***
*
* Función   : CONECTAR()
* Fecha     : 02/04/2019
* Autor     : Antonio C.
* Par metros: No tiene
* Devuelve  : Conexión con el servidor MYSQL usando ADO
* Uso       : Conexión con el servidor MYSQL usando ADO
*
*/

Function Conectar()
*-----------------------------------------------------------------------------*
Local oC,Servidor,BaseDatos,User,Pass,Engine

// Servidor := "127.0.0.1"
Servidor := cHostname
BaseDatos:= "gestion"
User     := "root"
Pass     := "Pepe"
Engine   := 'MYSQL'

oC := AdoConn( Servidor, BaseDatos, User, Pass, Engine )

Return oC

/* 
Funcion AdoConn realiza la conexion con el servidor
Parametros:
Server = Puede ser una direccion www.xxx.com o una IP o LocalHost
Database = Opcional - Nombre de la base de datos que deseen abrir
User = Nombre de usuario del servidor SQL
Pass = Contraseña del usuario
Port = Opcional - Puerto de acceso
Engine = Motor SQL a usar (MSSQL, MYSQL, MARIADB, etc) 
Nota: Yo uso MariaDB sin embargo conecto con MySQL. Parece ser mas avanzada su interface.
		Para usar MySql o MariaDb se debe descargar e instalar las interfaces ODBC 
			eg: mysql-connector-odbc-5.3.9-win32.msi
*/

Function AdoConn(Server, Database, User, Pass, Engine, Port)
Local oC, sConection, nOption

	oC := win_oleCreateObject( "ADODB.Connection" )
	oC:CursorLocation := adUseClient
	oC:ConnectionTimeout := 10
	oC:CommandTimeOut := 15 //30

	DO CASE
	CASE Engine  == "MARIADB"
		nOption := 3+4194304+67108864	// dont know + auto_reconect + multiple_statementes_allowed
		sconection := "Provider=MSDASQL;Driver={MariaDB ODBC 2.0 Driver};" + ;
							"Server=" + Server + ;
							";Database=" + Database + ;
							";User=" + User + ;
							";Password=" + Pass + ;
							";Option="+str(INT(nOption))+if(Port <> NIL, ";Port="+Port ,";")
	
	CASE Engine  == "MYSQL"
		nOption := 3+4194304+67108864	// dont know + auto_reconect + multiple_statementes_allowed
		sconection := "Provider=MSDASQL;Driver={MySQL ODBC 5.3 ANSI Driver};" + ;
							"Server=" + Server + ;
							";Database=" + Database + ;
							";User=" + User + ;
							";Password=" + Pass + ;
							";Option="+str(nOption)+if(Port <> NIL, ";Port="+Port ,"") +;
							";UseCompression=True;Pooling=True;"

	CASE Engine == "MSSQL"
		sconection := "Provider=SQLOLEDB;" + ;			//"Provider=SQLNCLI10;"  
							"server=" + server + if(Port <> NIL, ","+Port ,"") +;
							";database=" + if(EMPTY(database), "master", database) + ;
							iif(EMPTY(User), ";Integrated Security=SSPI;",";uid=" + User + ";pwd=" + Pass )
				
	CASE Engine == "SQLITE"		// No Probado
		sconection := "Driver={SQLite3 ODBC Driver};" + ;
							"Database=" + Database   + ;
							";LongNames=0;Timeout=1000;NoTXN=0;SyncPragma=NORMAL;StepAPI=0;" 

	ENDCASE
	oC:ConnectionString := sconection
	TRY
		oC:Open()
	Catch 	// oErr
		// Native Error 1045 = Denied access (user or password incorrect)
		// Native Error 160 = ODBC Driver not found
		msgbox(oC:Errors[0]:Description,"Native Error "+Str(oC:Errors[0]:NativeError) )
	END SEQUENCE 
Return oC

/* 
Function Ado()

Crea un recordset con los registros solicitados por cSql
Para mas información ver https://www.w3schools.com/asp/ado_ref_recordset.asp
Es importante ver los usos de CursorLocation, CursorType y LockType
*/
Function Ado(cSql, oC)
Local oRs
	oRs := win_oleCreateObject( "ADODB.Recordset" )
	oRs:CursorLocation 	:= adUseClient		// adUseServer
	oRs:CacheSize 			:= 50
	oRs:LockType 			:= adLockBatchOptimistic	// 1 adLockReadOnly 2 adLockPessimistic, 3 adLockOptimistic, 4 adLockBatchOptimistic
	oRs:CursorType 		:= adOpenStatic	// adOpenDynamic(2) adOpenStatic(3) adOpenKeyset(1) adOpenForwardOnly(0)
	oRs:ActiveConnection := oC
	
	oRs:Open( cSql )	//adAsyncFetch adAsyncExecute + 
Return oRs

/***/
static Function CrearTabla( oC )

local cQuery

cQuery:="Create Table CLIENTES1 ("+;
		 "CLIENTE      CHAR(6)      default ''," +;
		 "NOMBRE       VARCHAR(50)  default ''," +;
         "CLIENTES1_ID Int(10)      Unsigned Not Null auto_increment,Primary Key (CLIENTES1_ID))" +;
		 " ENGINE=InnoDB DEFAULT CHARSET=utf8"

TRY
  oRsBrw := DBADO():New(cQuery, oC)
Catch
  MsgStop(cQuery, "Error Comando SQL, Comprobantes en pantalla")
  Return
End Sequence

retu

/***/
static Function AgregaRegistros( oC )

FOR i := 1 TO 15
  cLetra:=chr(65 +i) +Str(HB_RandomInt( 999999 ),6)
  cQuery:="INSERT INTO clientes1 (cliente,nombre) VALUES ('" +Str(HB_RandomInt( 999999 ),6) +"','" +cLetra +"')"

  TRY
    oRsBrw := DBADO():New(cQuery, oC)
  Catch
    MsgStop(cQuery, "Error Comando SQL, Comprobantes en pantalla")
    Return
  End Sequence
NEXT i

retu

CLASS DBAdo
	DATA oRs
	DATA cAlias__ INIT nil
	
	METHOD New( cSql, oC )	INLINE ::oRs := ADO(cSql, oC), Self
	METHOD Skipper(nSkip)
	METHOD GoTop				INLINE if(::oRs:RecordCount > 0, ::oRs:MoveFirst(), )
	METHOD GoBottom			INLINE if(::oRs:RecordCount > 0, ::oRs:MoveLast(), )
	METHOD BOF					INLINE ::oRs:Bof
	METHOD EOF					INLINE ::oRs:Eof
	METHOD OrdKeyCount		INLINE ::oRs:RecordCount
	METHOD OrdKeyGoTo(n)		INLINE ::oRs:AbsolutePosition := n
	METHOD OrdKeyNo			INLINE ::oRs:AbsolutePosition 
	METHOD SKIP(n)				INLINE	n := IF(HB_ISNil(n), 1, n), ::oRs:Move(n)
	METHOD Close				INLINE ::oRs:Close()
ENDCLASS

METHOD Skipper( nSkip ) CLASS DBADO
LOCAL nCount:=0
	nSkip := INT( nSkip )
	IF nSkip > 0
	  DO WHILE nSkip > 0
		 ::oRs:Move( 1 )
		 IF ::oRs:Eof
			::oRs:Move( -1 )
			EXIT
		 ENDIF
		 nCount++
		 nSkip--
	  ENDDO
	ELSE
	  DO WHILE nSkip < 0
		 ::oRs:Move( -1 )
		 IF ::oRs:Bof
			::oRs:Move(1)
			EXIT
		 ENDIF
		 nCount--
		 nSkip++
	  ENDDO
	ENDIF
RETURN nCount
/*
Es un ejemplo modificado de David Field para usar ADO con MySQL. El problema surge al querer filtrar la tabla de clientes con el textbox buscar. Ahi ni bien pulso una tecla (que es una letra para filtrar por el nombre), ahi cancela
*/

**Comment by fyurisich** [comment]
Error occurs at a NAVIGATEBYCELL grid when

Do While oBrw:ColumnCount() > 0
  oBrw:DeleteColumn()
EndDo

Log entry:

Error irrecuperable 9023: hb_xgrab requirio apartar cero bytes
Called from LISTVIEW_GETCOLUMNORDER(0)
Called from TXBROWSEBYCELL:COLUMNORDER(2325) in h_grid.prg
Called from TXBROWSEBYCELL:FIRSTCOLINORDER(4391) in h_grid.prg
Called from TXBROWSEBYCELL:DELETECOLUMN(3190) in h_xbrowse.prg

Fixed. See 6878c019116bcbbb4bf90db5e29ff5e27316d312
