### ISSUE TITLE
Error buscando en XBROWSE con ADO MySQL

### ISSUE THREAD

**Issue by CITRO1965** [oohg/core#189]
#include "oohg.ch"
#include "adordd.ch"
#include "Hbclass.ch"

#xcommand TRY  => BEGIN SEQUENCE WITH {| oErr | Break( oErr ) }
#xcommand CATCH [<!oErr!>] => RECOVER [USING <oErr>] <-oErr->
#xcommand FINALLY => ALWAYS

/**
* Al buscar un producto ingresado en el primer textbox, luego de pulsar ENTER se despliega una 
* pantalla de búsqueda con una lista de posibles productos a seleccionar, al ir escribiendo el producto 
* en el textbox TXTBUSCAR del formulario FRMBUSQUEDA, en algún momento cancela con el 
* mensaje del error de la imágen que aparece al final del archivo.
*/
FUNCTION Main()

private xarti,oRsBrw,xbuscar

oC:= Conectar()
CrearTabla( oC )
AgregaRegistros( oC )

DEFINE WINDOW frmPr200123 OBJ oWndPr200123 ;
  AT 0,0 ;
  WIDTH 760 HEIGHT 600 ; 
  FONT "CONSOLAS" SIZE 11 ;    
  MAIN ;
  ON INIT {|| InitVars() } ;
  ON RELEASE Cierra_Ado( oC )

  DEFINE LABEL lblArti
    ROW 40
    COL 10 
    WIDTH 80
    VALUE "Artículo"
	AUTOSIZE .T.
  END LABEL
  
  DEFINE TEXTBOX txtArti
    ROW 40
    COL 100
    VALUE xarti
    WIDTH 160
	AUTOSKIP .T.
	ON LOSTFOCUS {|| Busqueda( oC ) } 
  END TEXTBOX
  
		 
  DEFINE BUTTON btnCancelar
    ROW 510
    COL 600
    CAPTION "&Salir"
    WIDTH 100 
	ACTION frmPr200123.release
	CANCEL .T.
  END BUTTON
		 
  DEFINE STATUSBAR OBJ oSTAT
    STATUSITEM 'Ctrl-Enter:Cancela Comprobante'
  END STATUSBAR

  ON KEY ESCAPE OF (oWndPr200123) ACTION oWndPr200123:Release()
         
END WINDOW
    
CENTER WINDOW frmPr200123
ACTIVATE WINDOW frmPr200123

RETURN

/***/
static Function Busqueda( oC )

local cSql

aHeaders:={'Artículo','Descripción'}
aWidths :={150,200}
aCtrl   :={ {'TEXTBOX', 'STRING','@R !!-!!!!!!!!!!!!!!'}, {'TEXTBOX', 'CHARACTER'} } 
aJusti  :={ GRID_JTFY_LEFT,GRID_JTFY_LEFT }
titulo  :='Artículos'
aFields :={}    

cSql:="SELECT articulo,nombre FROM stock1 LIMIT 20"

If !Hb_IsObject(oC)
  MsgStop("Es necesario realizar primeramente la conexion","Error")
  Return
Endif
      
TRY
  oRsBrw := DBADO():New(cSql, oC)
Catch
  MsgStop(cSql, "Error Comando SQL, Comprobantes en pantalla")
  Return
End Sequence

if !oRsBrw:oRs:Eof()
  For n := 1 TO oRsBrw:oRs:Fields:Count()
    AADD(aFields, &("{|wa| wa:oRs:Fields("+STR(n-1)+"):Value }"))
  Next n
end if

DEFINE WINDOW frmBusqueda ;
  OBJ ofrmBusqueda ;
  AT 0, 0 ;
  WIDTH 500 ;
  HEIGHT 500 ;
  TITLE titulo ;
  MODAL ;
  ON INIT InitVarsBusq() 
    
  @ 20,10 XBROWSE TbBusqueda ;
    OBJ oBrwBusqueda;
  	WIDTH ofrmBusqueda:ClientWidth - 40 ;
   	HEIGHT ofrmBusqueda:ClientHeight - 105 ;
   	WORKAREA ( oRsBrw  ) ;	
   	HEADERS aHeaders ;
   	FIELDS aFields ;
   	WIDTHS aWidths ; 
   	COLUMNCONTROLS aCtrl ;
   	JUSTIFY aJusti ; 
   	FIXEDBLOCKS ;
    NAVIGATEBYCELL
  
    @ ofrmBusqueda:ClientHeight - 64, ofrmBusqueda:ClientWidth - 230 BUTTON btnCancelar ;
      CAPTION "Salir" ;
      WIDTH 100 ;
      HEIGHT 24 ;
      ACTION ThisWindow.release()
  		 
    DEFINE LABEL lblBuscar
      ROW ofrmBusqueda:ClientHeight - 30
      COL 10
      VALUE "Buscar" 
      WIDTH 40 
    END LABEL
    	
    DEFINE TEXTBOX TxtBuscar
      ROW ofrmBusqueda:ClientHeight - 30
      COL 60
      WIDTH 200 
      VALUE xbuscar
      INPUTMASK replicate( "X",50 ) 
      TOOLTIP "Tipee el nombre del cÃ³digo a buscar"
  	AUTOSKIP .T.
  	ON CHANGE BuscaEnBrow( oC )
    END TEXTBOX
  
    ON KEY ESCAPE ACTION ofrmBusqueda:Release()
  	  
END WINDOW
  
ofrmBusqueda:Center()
ofrmBusqueda:Activate()

retu

/***/
static Function InitVars()

xarti:=space(16)
frmPr200123.txtArti.value:=xarti
frmPr200123.txtArti.setfocus

retu

/***/
static Function InitVarsBusq()

xbuscar:=space(30)
frmBusqueda.txtBuscar.value:=xbuscar

retu

/***/
static Function Cierra_Ado( oC )

oC:Close()

retu

/***/
static Function BuscaEnBrow( oC )

local cSql,n,cBuscar

cbuscar:=alltrim( frmBusqueda.txtBuscar.value )

aHeaders:={'Artículo','Descripción'}
aWidths :={150,350}
aCtrl   :={ {'TEXTBOX', 'STRING','@R !!-!!!!!!!!!!!!!!'}, {'TEXTBOX', 'CHARACTER'} } 
aJusti  :={ GRID_JTFY_LEFT,GRID_JTFY_LEFT }

cSql:="SELECT articulo,nombre FROM stock1 WHERE nombre LIKE '" +cbuscar +"%' ORDER BY articulo LIMIT 20"

Do while oBrwBusqueda:ColumnCount() > 0
  oBrwBusqueda:DeleteColumn()
end whil
oBrwBusqueda:deleteallitems()

TRY
  oRsBrw := DBADO():New(cSql,oC)
Catch
  MsgStop(cSql, "Error Comando SQL")
  Return
End Sequence

if !oRsBrw:oRs:Eof()
  oBrwBusqueda:WorkArea:= oRsBrw
  aFields:={}
  for n:=1 to oRsBrw:oRs:Fields:Count()
    oBrwBusqueda:AddColumn( n, &("{|wa| wa:oRs:Fields("+STR(n-1)+"):Value }"),aHeaders[n],aWidths[n],aJusti[n],,,,,aCtrl[n] )
  end for
  oBrwBusqueda:refresh()
end if
	
retu

/***/
static Function CrearTabla( oC )

local cQuery

cQuery:="Drop Table If Exists STOCK1"

oC:Execute( cQuery )

cQuery:="Create Table STOCK1 ("+;
		 "ARTICULO     VARCHAR(16)  default ''," +;
		 "NOMBRE       VARCHAR(50)   default ''," +;
         "STOCK1_ID Int(10)      Unsigned Not Null auto_increment,Primary Key (STOCK1_ID))" +;
		 "ENGINE=MyISAM DEFAULT CHARSET=utf8"

oC:Execute( cQuery )

cQuery:="CREATE INDEX ix_arti ON stock1(articulo)"
oC:Execute( cQuery )

cQuery:="CREATE INDEX ix_nombre ON stock1(nombre)"
oC:Execute( cQuery )

retu

/***/
static Function AgregaRegistros( oC )

FOR i := 1 TO 30000
  cLetra:=chr(65 +i) +Str(HB_RandomInt( 9999999 ),7)
  cQuery:="INSERT INTO stock1 (articulo,nombre) VALUES ('" +Str(HB_RandomInt( 9999999 ),7) +"','" 
  cQuery+="RE" +ltrim( str(HB_RandomInt( 9999999 ),16) ) +"')"
  
  oC:Execute( cQuery )
NEXT i

retu

/***
*
* FunciÃ³n   : CONECTAR()
* Fecha     : 02/04/2019
* Autor     : Antonio C.
* ParÂ metros: No tiene
* Devuelve  : ConexiÃ³n con el servidor MYSQL usando ADO
* Uso       : ConexiÃ³n con el servidor MYSQL usando ADO
*
*/

static Function Conectar()
*-----------------------------------------------------------------------------*
Local oC,Servidor,BaseDatos,User,Pass,Engine

Servidor := "127.0.0.1"
// Servidor := cHostname
BaseDatos:= "gestion"
User     := "root"
Pass     := "Pepe"
Engine   := 'MYSQL'

oC := AdoConn( Servidor, BaseDatos, User, Pass, Engine )

Return oC

/* 
Funcion AdoConn realiza la conexion con el servidor
Parametros:
Server = Puede ser una direccion www.xxx.com o una IP o LocalHost
Database = Opcional - Nombre de la base de datos que deseen abrir
User = Nombre de usuario del servidor SQL
Pass = ContraseÃ±a del usuario
Port = Opcional - Puerto de acceso
Engine = Motor SQL a usar (MSSQL, MYSQL, MARIADB, etc) 
Nota: Yo uso MariaDB sin embargo conecto con MySQL. Parece ser mas avanzada su interface.
		Para usar MySql o MariaDb se debe descargar e instalar las interfaces ODBC 
			eg: mysql-connector-odbc-5.3.9-win32.msi
*/

Function AdoConn(Server, Database, User, Pass, Engine, Port)
Local oC, sConection, nOption

	oC := win_oleCreateObject( "ADODB.Connection" )
	oC:CursorLocation := adUseClient
	oC:ConnectionTimeout := 10
	oC:CommandTimeOut := 15 //30

	DO CASE
	CASE Engine  == "MARIADB"
		nOption := 3+4194304+67108864	// dont know + auto_reconect + multiple_statementes_allowed
		sconection := "Provider=MSDASQL;Driver={MariaDB ODBC 2.0 Driver};" + ;
							"Server=" + Server + ;
							";Database=" + Database + ;
							";User=" + User + ;
							";Password=" + Pass + ;
							";Option="+str(INT(nOption))+if(Port <> NIL, ";Port="+Port ,";")
	
	CASE Engine  == "MYSQL"
		nOption := 3+4194304+67108864	// dont know + auto_reconect + multiple_statementes_allowed
		sconection := "Provider=MSDASQL;Driver={MySQL ODBC 5.3 ANSI Driver};" + ;
							"Server=" + Server + ;
							";Database=" + Database + ;
							";User=" + User + ;
							";Password=" + Pass + ;
							";Option="+str(nOption)+if(Port <> NIL, ";Port="+Port ,"") +;
							";UseCompression=True;Pooling=True;"

	CASE Engine == "MSSQL"
		sconection := "Provider=SQLOLEDB;" + ;			//"Provider=SQLNCLI10;"  
							"server=" + server + if(Port <> NIL, ","+Port ,"") +;
							";database=" + if(EMPTY(database), "master", database) + ;
							iif(EMPTY(User), ";Integrated Security=SSPI;",";uid=" + User + ";pwd=" + Pass )
				
	CASE Engine == "SQLITE"		// No Probado
		sconection := "Driver={SQLite3 ODBC Driver};" + ;
							"Database=" + Database   + ;
							";LongNames=0;Timeout=1000;NoTXN=0;SyncPragma=NORMAL;StepAPI=0;" 

	ENDCASE
	oC:ConnectionString := sconection
	TRY
		oC:Open()
	Catch 	// oErr
		// Native Error 1045 = Denied access (user or password incorrect)
		// Native Error 160 = ODBC Driver not found
		msgbox(oC:Errors[0]:Description,"Native Error "+Str(oC:Errors[0]:NativeError) )
	END SEQUENCE 
Return oC

/* 
Function Ado()

Crea un recordset con los registros solicitados por cSql
Para mas informaciÃ³n ver https://www.w3schools.com/asp/ado_ref_recordset.asp
Es importante ver los usos de CursorLocation, CursorType y LockType
*/
Function Ado(cSql, oC)
Local oRs
	oRs := win_oleCreateObject( "ADODB.Recordset" )
	oRs:CursorLocation 	:= adUseClient		// adUseServer
	oRs:CacheSize 			:= 50
	oRs:LockType 			:= adLockBatchOptimistic	// 1 adLockReadOnly 2 adLockPessimistic, 3 adLockOptimistic, 4 adLockBatchOptimistic
	oRs:CursorType 		:= adOpenStatic	// adOpenDynamic(2) adOpenStatic(3) adOpenKeyset(1) adOpenForwardOnly(0)
	oRs:ActiveConnection := oC
	
	oRs:Open( cSql )	//adAsyncFetch adAsyncExecute + 
Return oRs

CLASS DBAdo
	DATA oRs
	DATA cAlias__ INIT nil
	
	METHOD New( cSql, oC )	INLINE ::oRs := ADO(cSql, oC), Self
	METHOD Skipper(nSkip)
	METHOD GoTop				INLINE if(::oRs:RecordCount > 0, ::oRs:MoveFirst(), )
	METHOD GoBottom			INLINE if(::oRs:RecordCount > 0, ::oRs:MoveLast(), )
	METHOD BOF					INLINE ::oRs:Bof
	METHOD EOF					INLINE ::oRs:Eof
	METHOD OrdKeyCount		INLINE ::oRs:RecordCount
	METHOD OrdKeyGoTo(n)		INLINE ::oRs:AbsolutePosition := n
	METHOD OrdKeyNo			INLINE ::oRs:AbsolutePosition 
	METHOD SKIP(n)				INLINE	n := IF(HB_ISNil(n), 1, n), ::oRs:Move(n)
	METHOD Close				INLINE ::oRs:Close()
ENDCLASS

METHOD Skipper( nSkip ) CLASS DBADO
LOCAL nCount:=0
	nSkip := INT( nSkip )
	IF nSkip > 0
	  DO WHILE nSkip > 0
		 ::oRs:Move( 1 )
		 IF ::oRs:Eof
			::oRs:Move( -1 )
			EXIT
		 ENDIF
		 nCount++
		 nSkip--
	  ENDDO
	ELSE
	  DO WHILE nSkip < 0
		 ::oRs:Move( -1 )
		 IF ::oRs:Bof
			::oRs:Move(1)
			EXIT
		 ENDIF
		 nCount--
		 nSkip++
	  ENDDO
	ENDIF
RETURN nCount
![imagen](https://user-images.githubusercontent.com/58994713/73173748-d9432980-40e4-11ea-85a8-518523c44b4d.png)

**Comment by fyurisich** [comment]
No me es posible probar el ejemplo ya que no tengo MySQL instalado. Por
favor modifica el ejemplo utilizando Dbf.

Saludos
Fernando Yurisich

**Comment by CITRO1965** [comment]
Hola Fernando. Modifiqué el ejemplo para adaptarlo a DBF, y ahi no aparece el problema, funciona perfectamente. Es evidente que es algo que tiene que ver con ADO. Ahi igual subí otro ejemplo con las modificaciones que me sugirió David Field, pero lo único que cambió fue el error que aparece que en este caso es:

Error WINOLE/1007  El valor de BOF o EOF es True, o el actual registro se eliminó; la operación solicitada requiere un registro actual. (0x800A0BCD): ADODB.Field (DOS Error -2147352567)

Gracias igual.

**Comment by fyurisich** [comment]
Nothing to fix!
