### ISSUE TITLE
Error buscando en XBROWSE con ADO MySQL parte 2

### ISSUE THREAD

**Issue by CITRO1965** [oohg/core#190]
#include "oohg.ch"
#include "adordd.ch"
#include "Hbclass.ch"

#xcommand TRY  => BEGIN SEQUENCE WITH {| oErr | Break( oErr ) }
#xcommand CATCH [<!oErr!>] => RECOVER [USING <oErr>] <-oErr->
#xcommand FINALLY => ALWAYS

/**
* Luego de ingresar cualquier valor en el primer TEXTBOX que aparece en pantalla, al darle ENTER 
* despliega la pantalla con los productos a buscar, en el TEXTBOX del formulario de búsqueda al 
* empezar a escribir y luego de ingresar las 2 primeras letras, cualquier letra, despliega este error
* Error WINOLE/1007  El valor de BOF o EOF es True, o el actual registro se eliminó; la operación 
* solicitada requiere un registro actual. (0x800A0BCD): ADODB.Field (DOS Error -2147352567)
*/
FUNCTION Main()

SetXBrowseFixedBlocks( .T. )                // para que xbrowse solo cree un bloque
SetXBrowseFixedControls( .T. )         // para que xBrowse solo cree una vez los controles de edicion  

private xarti,oRsBrw,xbuscar

oC:= Conectar()
CrearTabla( oC )
AgregaRegistros( oC )

DEFINE WINDOW frmPr200123 OBJ oWndPr200123 ;
  AT 0,0 ;
  WIDTH 760 HEIGHT 600 ; 
  FONT "CONSOLAS" SIZE 11 ;    
  MAIN ;
  ON INIT {|| InitVars() } ;
  ON RELEASE Cierra_Ado( oC )

  DEFINE LABEL lblArti
    ROW 40
    COL 10 
    WIDTH 80
    VALUE "Artículo"
	AUTOSIZE .T.
  END LABEL
  
  DEFINE TEXTBOX txtArti
    ROW 40
    COL 100
    VALUE xarti
    WIDTH 160
	AUTOSKIP .T.
	ON ENTER {|| Busqueda( oC ) } // ON LOSTFOCUS {|| Busqueda( oC ) } 
  END TEXTBOX
  
		 
  DEFINE BUTTON btnCancelar
    ROW 510
    COL 600
    CAPTION "&Salir"
    WIDTH 100 
	ACTION frmPr200123.release
	CANCEL .T.
  END BUTTON
		 
  DEFINE STATUSBAR OBJ oSTAT
    STATUSITEM 'Ctrl-Enter:Cancela Comprobante'
  END STATUSBAR

  ON KEY ESCAPE OF (oWndPr200123) ACTION oWndPr200123:Release()
         
END WINDOW
    
CENTER WINDOW frmPr200123
ACTIVATE WINDOW frmPr200123

RETURN

/***/
static Function Busqueda( oC )

local cSql

aHeaders:={'Artículo','Descripción'}
aWidths :={150,200}
aCtrl   :={ {'TEXTBOX', 'STRING','@R !!-!!!!!!!!!!!!!!'}, {'TEXTBOX', 'CHARACTER'} } 
aJusti  :={ GRID_JTFY_LEFT,GRID_JTFY_LEFT }
titulo  :='Artículos'
aFields :={}    

cSql:="SELECT articulo,nombre FROM stock1 LIMIT 20"

If !Hb_IsObject(oC)
  MsgStop("Es necesario realizar primeramente la conexion","Error")
  Return
Endif
      
TRY
  oRsBrw := DBADO():New(cSql, oC)
Catch
  MsgStop(cSql, "Error Comando SQL, Comprobantes en pantalla")
  Return
End Sequence

if !oRsBrw:oRs:Eof()
  For n := 1 TO oRsBrw:oRs:Fields:Count()
    AADD(aFields, &("{|wa| wa:oRs:Fields("+STR(n-1)+"):Value }"))
  Next n
end if

IF !ISWINDOWDEFINED( "FrmBusqueda" )			 
  DEFINE WINDOW frmBusqueda ;
    OBJ ofrmBusqueda ;
    AT 0, 0 ;
    WIDTH 500 ;
    HEIGHT 500 ;
    TITLE titulo ;
    MODAL ;
    ON INIT InitVarsBusq() 
      
    @ 20,10 XBROWSE TbBusqueda ;
      OBJ oBrwBusqueda;
    	WIDTH ofrmBusqueda:ClientWidth - 40 ;
     	HEIGHT ofrmBusqueda:ClientHeight - 105 ;
     	WORKAREA ( oRsBrw  ) ;	
     	HEADERS aHeaders ;
     	FIELDS aFields ;
     	WIDTHS aWidths ; 
     	COLUMNCONTROLS aCtrl ;
     	JUSTIFY aJusti ; //      	FIXEDBLOCKS ;
      NAVIGATEBYCELL
    
      @ ofrmBusqueda:ClientHeight - 64, ofrmBusqueda:ClientWidth - 230 BUTTON btnCancelar ;
        CAPTION "Salir" ;
        WIDTH 100 ;
        HEIGHT 24 ;
        ACTION ThisWindow.release()
    		 
      DEFINE LABEL lblBuscar
        ROW ofrmBusqueda:ClientHeight - 30
        COL 10
        VALUE "Buscar" 
        WIDTH 40 
      END LABEL
      	
      DEFINE TEXTBOX TxtBuscar
        ROW ofrmBusqueda:ClientHeight - 30
        COL 60
        WIDTH 200 
        VALUE xbuscar
        INPUTMASK replicate( "X",50 ) 
        TOOLTIP "Tipee el nombre del cÃƒÂ³digo a buscar"
    	AUTOSKIP .T.
    	ON CHANGE BuscaEnBrow( oC )
      END TEXTBOX
    
      ON KEY ESCAPE ACTION ofrmBusqueda:Release()
    	  
  END WINDOW
    
  ofrmBusqueda:Center()
  ofrmBusqueda:Activate()
ELSE
  RESTORE WINDOW frmBusqueda
ENDIF

retu

/***/
static Function InitVars()

xarti:=space(16)
frmPr200123.txtArti.value:=xarti
frmPr200123.txtArti.setfocus

retu

/***/
static Function InitVarsBusq()

xbuscar:=space(30)
frmBusqueda.txtBuscar.value:=xbuscar

retu

/***/
static Function Cierra_Ado( oC )

oC:Close()

retu

/***/
static Function BuscaEnBrow( oC )

local cSql,n,cBuscar

cbuscar:=alltrim( frmBusqueda.txtBuscar.value )

cSql:="SELECT articulo,nombre FROM stock1 WHERE nombre LIKE '" +cbuscar +"%' ORDER BY articulo LIMIT 20"

TRY
  oRsBrw := DBADO():New(cSql,oC)
Catch
  MsgStop(cSql, "Error Comando SQL")
  Return
End Sequence
oBrwBusqueda:WorkArea:= oRsBrw
oBrwBusqueda:refresh()

retu

/***/
static Function CrearTabla( oC )

local cQuery

cQuery:="Drop Table If Exists STOCK1"

oC:Execute( cQuery )

cQuery:="Create Table STOCK1 ("+;
		 "ARTICULO     VARCHAR(16)  default ''," +;
		 "NOMBRE       VARCHAR(50)   default ''," +;
         "STOCK1_ID Int(10)      Unsigned Not Null auto_increment,Primary Key (STOCK1_ID))" +;
		 "ENGINE=MyISAM DEFAULT CHARSET=utf8"

oC:Execute( cQuery )

cQuery:="CREATE INDEX ix_arti ON stock1(articulo)"
oC:Execute( cQuery )

cQuery:="CREATE INDEX ix_nombre ON stock1(nombre)"
oC:Execute( cQuery )

retu

/***/
static Function AgregaRegistros( oC )

FOR i := 1 TO 30000
  cLetra:=chr(65 +i) +Str(HB_RandomInt( 9999999 ),7)
  cQuery:="INSERT INTO stock1 (articulo,nombre) VALUES ('" +Str(HB_RandomInt( 9999999 ),7) +"','" 
  cQuery+="RE" +ltrim( str(HB_RandomInt( 9999999 ),16) ) +"')"
  
  oC:Execute( cQuery )
NEXT i

retu

/***
*
* FunciÃƒÂ³n   : CONECTAR()
* Fecha     : 02/04/2019
* Autor     : Antonio C.
* ParÃ‚ metros: No tiene
* Devuelve  : ConexiÃƒÂ³n con el servidor MYSQL usando ADO
* Uso       : ConexiÃƒÂ³n con el servidor MYSQL usando ADO
*
*/

static Function Conectar()
*-----------------------------------------------------------------------------*
Local oC,Servidor,BaseDatos,User,Pass,Engine

Servidor := "127.0.0.1"
// Servidor := cHostname
BaseDatos:= "gestion"
User     := "root"
Pass     := "Pepe"
Engine   := 'MYSQL'

oC := AdoConn( Servidor, BaseDatos, User, Pass, Engine )

Return oC

/* 
Funcion AdoConn realiza la conexion con el servidor
Parametros:
Server = Puede ser una direccion www.xxx.com o una IP o LocalHost
Database = Opcional - Nombre de la base de datos que deseen abrir
User = Nombre de usuario del servidor SQL
Pass = ContraseÃƒÂ±a del usuario
Port = Opcional - Puerto de acceso
Engine = Motor SQL a usar (MSSQL, MYSQL, MARIADB, etc) 
Nota: Yo uso MariaDB sin embargo conecto con MySQL. Parece ser mas avanzada su interface.
		Para usar MySql o MariaDb se debe descargar e instalar las interfaces ODBC 
			eg: mysql-connector-odbc-5.3.9-win32.msi
*/

Function AdoConn(Server, Database, User, Pass, Engine, Port)
Local oC, sConection, nOption

	oC := win_oleCreateObject( "ADODB.Connection" )
	oC:CursorLocation := adUseClient
	oC:ConnectionTimeout := 10
	oC:CommandTimeOut := 15 //30

	DO CASE
	CASE Engine  == "MARIADB"
		nOption := 3+4194304+67108864	// dont know + auto_reconect + multiple_statementes_allowed
		sconection := "Provider=MSDASQL;Driver={MariaDB ODBC 2.0 Driver};" + ;
							"Server=" + Server + ;
							";Database=" + Database + ;
							";User=" + User + ;
							";Password=" + Pass + ;
							";Option="+str(INT(nOption))+if(Port <> NIL, ";Port="+Port ,";")
	
	CASE Engine  == "MYSQL"
		nOption := 3+4194304+67108864	// dont know + auto_reconect + multiple_statementes_allowed
		sconection := "Provider=MSDASQL;Driver={MySQL ODBC 5.3 ANSI Driver};" + ;
							"Server=" + Server + ;
							";Database=" + Database + ;
							";User=" + User + ;
							";Password=" + Pass + ;
							";Option="+str(nOption)+if(Port <> NIL, ";Port="+Port ,"") +;
							";UseCompression=True;Pooling=True;"

	CASE Engine == "MSSQL"
		sconection := "Provider=SQLOLEDB;" + ;			//"Provider=SQLNCLI10;"  
							"server=" + server + if(Port <> NIL, ","+Port ,"") +;
							";database=" + if(EMPTY(database), "master", database) + ;
							iif(EMPTY(User), ";Integrated Security=SSPI;",";uid=" + User + ";pwd=" + Pass )
				
	CASE Engine == "SQLITE"		// No Probado
		sconection := "Driver={SQLite3 ODBC Driver};" + ;
							"Database=" + Database   + ;
							";LongNames=0;Timeout=1000;NoTXN=0;SyncPragma=NORMAL;StepAPI=0;" 

	ENDCASE
	oC:ConnectionString := sconection
	
	TRY
		oC:Open()
	Catch 	// oErr
		// Native Error 1045 = Denied access (user or password incorrect)
		// Native Error 160 = ODBC Driver not found
		msgbox(oC:Errors[0]:Description,"Native Error "+Str(oC:Errors[0]:NativeError) )
	END SEQUENCE 
	
Return oC

/* 
Function Ado()

Crea un recordset con los registros solicitados por cSql
Para mas informaciÃƒÂ³n ver https://www.w3schools.com/asp/ado_ref_recordset.asp
Es importante ver los usos de CursorLocation, CursorType y LockType
*/
Function Ado(cSql, oC)
Local oRs
	oRs := win_oleCreateObject( "ADODB.Recordset" )
	oRs:CursorLocation 	:= adUseClient		// adUseServer
	oRs:CacheSize 			:= 50
	oRs:LockType 			:= adLockBatchOptimistic	// 1 adLockReadOnly 2 adLockPessimistic, 3 adLockOptimistic, 4 adLockBatchOptimistic
	oRs:CursorType 		:= adOpenStatic	// adOpenDynamic(2) adOpenStatic(3) adOpenKeyset(1) adOpenForwardOnly(0)
	oRs:ActiveConnection := oC
	
	oRs:Open( cSql )	//adAsyncFetch adAsyncExecute + 
Return oRs

CLASS DBAdo
	DATA oRs
	DATA cAlias__ INIT nil
	
	METHOD New( cSql, oC )	INLINE ::oRs := ADO(cSql, oC), Self
	METHOD Skipper(nSkip)
	METHOD GoTop				INLINE if(::oRs:RecordCount > 0, ::oRs:MoveFirst(), )
	METHOD GoBottom			INLINE if(::oRs:RecordCount > 0, ::oRs:MoveLast(), )
	METHOD BOF					INLINE ::oRs:Bof
	METHOD EOF					INLINE ::oRs:Eof
	METHOD OrdKeyCount		INLINE ::oRs:RecordCount
	METHOD OrdKeyGoTo(n)		INLINE ::oRs:AbsolutePosition := n
	METHOD OrdKeyNo			INLINE ::oRs:AbsolutePosition 
	METHOD SKIP(n)				INLINE	n := IF(HB_ISNil(n), 1, n), ::oRs:Move(n)
	METHOD Close				INLINE ::oRs:Close()
ENDCLASS

METHOD Function Skipper(nSkip) CLASS DBADO
*-----------------------------------------------------------------------------*
Local n := 0,  oRs
    oRs := ::oRs

*    IF nSkip != 0
        // Esto es necesario para cuando el recordset está vacio, de lo contrario da error
        IF (oRs:EOF .and. nSkip > 0) .or. (oRs:BOF .and. nSkip < 0)
            Return 0
        ENDIF
        // Fin necesario
       
        While nSkip <> n
            IF nSkip > 0
                oRs:Move( 1 )
                If oRs:EOF
                    oRs:Move(-1)    // Enero/2020
                    exit
                Else
                    n ++
                Endif
            ELSE    //IF nSkip < 0 .AND. !oRs:Bof
                oRs:Move(-1)
                IF oRs:BOF       
                    oRs:Move(1)
                    Exit
                Else
                    n --
                Endif
            ENDIF
        ENDDO
        nSkip := n
*    ENDIF

Return nSkip        
/*
Ahora me arroja este error:
![imagen](https://user-images.githubusercontent.com/58994713/73127446-20bf9d80-3f9f-11ea-80c5-e60a319eccfc.png)
*/

**Comment by fyurisich** [comment]
See #189
