### ISSUE TITLE
Combobox no carga todos los items de una tabla indexada

### ISSUE THREAD

**Issue by pbruccoleri** [oohg/core#192]
Este combobox asociado a una tabla no carga todos los items; solo los 3 primeros.

   @ 169, 454 COMBOBOX interrup_cmb ;
      WIDTH 130 ;
      ITEMSOURCE interrup->nombre ;
      VALUESOURCE interrup->codigo ;
      FONT 'MS Sans Serif' ;
      FONTCOLOR {  0,  0,  0} ;
      BACKCOLOR {255,255,255}

**Comment by fyurisich** [comment]
Por favor sube un ejemplo compilable.
Gracias

**Comment by pbruccoleri** [comment]
A Partir del sample 006 hice este
[s06.zip](https://github.com/oohg/core/files/4159567/s06.zip)
 ejemplo.
Si solo tomo el ejemplo, funciona todo OK. Cuando está armado de esta forma, o sea hay un form principal, menú, etc, es que no funciona como corresponde.

**Comment by fyurisich** [comment]
Fixed. See feb7ea285550000d104e5a79f0b0e83dfe499e4f
