### ISSUE TITLE
archivo .RC no funciona

### ISSUE THREAD

**Issue by dextrasistemas** [oohg/core#193]
Fernando
 
 Aca va mi "issue"
 Es simple , los archivos RC  ( recursos ) no funcionan olimpicamente
 Probé y probe...
 Te envié por el otro sitio un ejemplo muy sencillo

Saludos
Jorge

**Comment by fyurisich** [comment]
[per_cpr.zip](https://github.com/oohg/core/files/4201897/per_cpr.zip)
Test program.

**Comment by fyurisich** [comment]
See attached image for error description.
![error](https://user-images.githubusercontent.com/3884477/74487581-9633d500-4e9e-11ea-9196-1a8eb67e25d4.png)

**Comment by fyurisich** [comment]
Fixed. See 89fe4b7c19a89f139d42e9b97735d14f0d317802
