### ISSUE TITLE
Archivo de recursos - necesidad que funcione como tal

### ISSUE THREAD

**Issue by dextrasistemas** [oohg/core#194]
Fernando

 Con  El tema del archivo de recursos que no funciona, que debo hacer
 al momento no he entendido ,  es un problema de mi pc/instalacion
 y vos no podes hacer nada ? 

Jorge Accinelli

**Comment by fyurisich** [comment]
Debes actualizar las librerías a partir de los últimos fuentes que están en GitHub.
Para ello sigue las instrucciones del documento 
https://github.com/oohg/doc/blob/master/english/Install_and_Update.md
