### ISSUE TITLE
archivo de recursos no funciona aun actualizando oohg

### ISSUE THREAD

**Issue by dextrasistemas** [oohg/core#195]
Fernando

   He actualizado oohg segun el paper y sigue sin funcionar el archivo de recursos
  La aplicacion que te envié funciona bien en tu entorno ?
  Puede ser alguna razon ajena a oohg ? 

 Si podes enviame las librerias correctamente generadas ( quiza yo cometa algun error
 dificil porque el paper es claro ) y un .rc de ejemplo. Asi, si no me funciona
 ya se que es mi equipo. 

 Gracias
Jorge Accinelli

 

  

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fyurisich** [comment]
Si, la aplicación funciona bien con el arreglo que subí ayer.
No tengo idea de si puede ser por alguna razón ajena.
Disculpa pero no puedo enviártelas, estoy con muy poco tiempo disponible, y solo estoy realizando los arreglos imprescindibles en OOHG .
El ejemplo que enviaste, compilado con las herramientas de OOHG, funciona OK.
Te aconsejo que pruebes a compilar utilizando el COMPILE.BAT de oohg.
Saludos
