### ISSUE TITLE
Error: Non top modal window *NULL0000000599* can't be released. Program terminated.

### ISSUE THREAD

**Issue by jimeneztatodavid** [oohg/core#197]
Buenas a todos, mi aplicacion ha lanzado este error y no se a que puede corresponder. Es la primera vez que lo veo y no ha vuelto a suceder más en varios dias.

Application: Z:\gestionlab\laboratorio.exe
Date: 03/03/2020 Time: 09:22:07
Version: OOHG Ver. 2019.02.27
Alias in use: DETERTMP
Computer Name: TERE
User Name: TERE
Error: Non top modal window *NULL0000000599* can't be released. Program terminated.
Called from TFORMMODAL:RELEASE (2201) in h_form.prg
Called from TGRIDCONTROLTEXTBOX:VALID (6434) in h_grid.prg
Called from (b)TGRIDCONTROLTEXTBOX_CREATEWINDOW (6579) in h_grid.prg
Called from (b)TGRIDCONTROLTEXTBOX_CREATEWINDOW (6594) in h_grid.prg
Called from (b)EVAL (0)
Called from _OOHG_EVAL_ARRAY (0)
Called from TFORMMODAL:DOEVENT (1118) in h_form.prg
Called from LOOKFORKEY_CHECK_HOTKEY (768) in h_windows.prg
Called from TFORMMODAL:LOOKFORKEY (741) in h_windows.prg
Called from TTEXTPICTURE:LOOKFORKEY (748) in h_windows.prg
Called from _OOHG_DOMESSAGELOOP (0)
Called from TFORMMODAL:MESSAGELOOP (647) in h_form.prg
Called from TFORM:ACTIVATE (621) in h_form.prg
Called from TFORMMODAL:ACTIVATE (2195) in h_form.prg
Called from TGRIDCONTROLTEXTBOX:CREATEWINDOW (6663) in h_grid.prg
Called from TOBROWSE:EDITCELL2 (2685) in h_grid.prg
Called from TXBROWSE:EDITCELL (2023) in h_xbrowse.prg
Called from TOBROWSE:EDITCELL (1105) in h_browse.prg
Called from TOBROWSE:EDITGRID (1388) in h_browse.prg
Called from TOBROWSE:APPENDITEM (1578) in h_xbrowse.prg
Called from TOBROWSE:EVENTS_NOTIFY (2126) in h_browse.prg
Called from TWINDOW:EVENTS (0) in h_windows.prg
Called from _OOHG_TFORM_EVENTS2 (1813) in h_form.prg
Called from TFORMMODAL:EVENTS (0) in h_form.prg
Called from _OOHG_DOMESSAGELOOP (0)
Called from TFORMMODAL:MESSAGELOOP (647) in h_form.prg
Called from _ACTIVATEWINDOW (2868) in h_form.prg
Called from MODIFICAANALISIS (2511) in Z:\OOHG\PROGRAMAS\LABORATORIO\analisis.prg
Called from (b)ENTRADAANALISIS (89) in Z:\OOHG\PROGRAMAS\LABORATORIO\analisis.prg
Called from (b)EVAL (0)
Called from _OOHG_EVAL_ARRAY (0)
Called from TTOOLBUTTON:DOEVENT (1930) in h_controlmisc.prg
Called from TTOOLBUTTON:DOEVENTMOUSECOORDS (1946) in h_controlmisc.prg
Called from TTOOLBAR:EVENTS_COMMAND (310) in h_toolbar.prg
Called from TWINDOW:EVENTS (0) in h_windows.prg
Called from _OOHG_TFORM_EVENTS2 (1813) in h_form.prg
Called from TFORM:EVENTS (0) in h_form.prg
Called from _OOHG_DOMESSAGELOOP (0)
Called from TFORMMAIN:MESSAGELOOP (647) in h_form.prg
Called from _ACTIVATEWINDOW (2868) in h_form.prg
Called from MAIN (396) in Z:\OOHG\PROGRAMAS\LABORATORIO\laboratorio.PRG --

**Comment by fyurisich** [comment]
Por favor agrega un programa ejemplo que muestre el error para hacer pruebas.

**Comment by jimeneztatodavid** [comment]
Fernando el añadir un programa ejemplo que muestre el error no se como hacerlo ya que, después de varios dias, no a vuelto a suceder.

Si te sirve de algo, la ventana NULL0000000599 no esta definida en mi programa en ningún lado.

Saludos.

**Comment by fyurisich** [comment]
Sin ejemplo no me es posible hacer ninguna corrección.
El dato del nombre de la ventana no aporta a solucionar el problema.
Del log de errores lo que puedo sacar es que se produce al agregar un registro en un XBrowse utilizando un Textbox y que durante el evento VALID del mismo estarías cancelando la edición.
Te aconsejo que cambies la lógica de tu programa: no canceles la edición y en su lugar devuelve .F. para que el usuario decida si ingresa un dato correcto o si cancela la edición.
