### ISSUE TITLE
Imprimir una imagen guardada en archivo RC

### ISSUE THREAD

**Issue by ViCagCan** [oohg/core#201]
Revisando el ejemplo nº 13 veo que algo no funciona correctamente o a lo mejor si lo está haciendo y no es lo que yo busco.

Llevo tiempo queriendo introducir en un archivo RC una serie de imágenes para que sean impresas en unos documentos. Dichas imágenes no pueden estar en una carpeta para que sean tomadas de ese lugar y enviadas a imprimir ya que es necesario tener la "seguridad" de que no han sido manipuladas.

Revisando el ejemplo indicado veo que si imprime la imagen pero... no el resto del listado, es decir...
Al ejemplo yo le he añadido un par de líneas de texto de prueba, una anterior a la imagen y otra posterior. Una vez ejecuta<do lo que hace es imprimir las líneas añadidas de texto pero no así la imagen. Si se quitan estas líneas si se imprime la imagen pero sin posibilidad de poner un texto acompañando a dicha imagen.

Este es el ejemplo con la pequeña ,modificación...

/*
 * Image Sample # 13
 * Author: Fernando Yurisich <fyurisich@oohg.org>
 * Licensed under The Code Project Open License (CPOL) 1.02
 * See <http://www.codeproject.com/info/cpol10.aspx>
 *
 * This sample shows how to print an image using its handle.
 *
 * Visit us at https://github.com/oohg/samples
 *
 * You can download oohg.jpg and s013.rc from:
 * https://github.com/oohg/samples/tree/master/Image
 */

#include "oohg.ch"

FUNCTION Main

   DEFINE WINDOW Form_1 ;
      AT 0, 0 ;
      WIDTH 640 ;
      HEIGHT 480 ;
      CLIENTAREA ;
      TITLE "ooHG - Print an Image using it's handle or from resources" ;
      MAIN

      @ 20, 20 IMAGE 0 ;
         OBJ oImage ;
         IMAGESIZE ;
         PICTURE "oohg.jpg"

      @ 20, 220 IMAGE 0 ;
         IMAGESIZE ;
         PICTURE "HARBOUR"

      @ 200, 20 BUTTON 0 ;
         WIDTH 150 ;
         CAPTION "Print" ;
         ACTION Print( "HBPRINTER" )

      @ 250, 20 CHECKBOX 0 ;
         OBJ oCheck ;
         CAPTION "Image Size"

      ON KEY ESCAPE ACTION Form_1.Release()
   END WINDOW

   CENTER WINDOW Form_1
   ACTIVATE WINDOW Form_1

   RETURN NIL

PROCEDURE Print( cTPrintLib )

   LOCAL oPrint := TPrint( cTPrintLib )

   oPrint:Init()

   oPrint:SelPrinter( .T., .T. )
   IF oPrint:lPrError
      oPrint:Release()
      RETURN
   ENDIF

   oPrint:BeginDoc()
   oPrint:BeginPage()
   oPrint:PrintData(10,60,"Esto es una prueba linea 1","times new roman",8,,,"L")
   oPrint:PrintData(20, 10, "Image from handle" )
   oPrint:PrintBitmap(30, 10, 16, 30, oImage:hBitmap, , , , , oCheck:Value )
   oPrint:PrintData( 40, 10, "Image from resource" )
   oPrint:PrintResource( 50, 10, 31, 70, "HARBOUR", , , , , , , , , oCheck:Value )
   oPrint:PrintData(100,60,"Esto es una prueba linea 2","times new roman",8,,,"L")
   oPrint:EndPage()
   oPrint:EndDoc()

   oPrint:Release()

   RETURN

/*
 * EOF
 */

Es un error o está pensado tal cual actua el ejemplo?

Un saludo.

**Comment by fyurisich** [comment]
Fixed. See a191644356bdf2b443fd04431be54623fc9612ad
