### ISSUE TITLE
Please, I humbly request your help

### ISSUE THREAD

**Issue by dextrasistemas** [oohg/core#202]
** Describe your request **
Write a clear and concise description of your request.
Explain what is happening and what you expected to happen.

** How to reproduce and test **
Add a PRG file (minimal, self-contained, and compilable) that shows what you are trying to do or achieve.
Detail the steps to build, run, and test.

** Additional Information **
Add any additional information (including screenshots) to help explain your request.

**Comment by fyurisich** [comment]
#204
