### ISSUE TITLE
Fernando: Noté que las librerias de la carpeta C:\oohg\hb32\lib\win\mingw, que son 40 archivos menos que la anterior que usaba, ignora la clase Tmysqlserver olímpicamente. Como puedo agregar manteniendo toda la distro con lo mas nuevo esa clase ? Saludos Jorge 

### ISSUE THREAD

**Issue by dextrasistemas** [oohg/core#204]
** Describe your request **
Write a clear and concise description of your request.
Explain what is happening and what you expected to happen.

** How to reproduce and test **
Add a PRG file (minimal, self-contained, and compilable) that shows what you are trying to do or achieve.
Detail the steps to build, run, and test.

** Additional Information **
Add any additional information (including screenshots) to help explain your request.

**Comment by fyurisich** [comment]
Jorge, debes conseguir, o crear, una distribución de Harbour que contenga dicha librería y luego recompilar OOHG.
Saludos, Fernando.
