### ISSUE TITLE
Error: COMBOBOX: The valtype of the first item is not valid. Program terminated.

### ISSUE THREAD

**Issue by pbruccoleri** [oohg/core#205]
on un combobox definido de esta forma:
   @ 156, 310 COMBOBOX codplan_cmb ;
      WIDTH 150 ;
      ITEMSOURCE "planes->nombre" ;
      VALUE 1 ;
      VALUESOURCE "planes->plan" ;
      FONT 'MS Sans Serif' ;
      SIZE 9 ;
      ON GOTFOCUS { || This.BackColor:=clrBack  } ;
      ON LOSTFOCUS { || This.BackColor:=clrNormal } ;
      FONTCOLOR {  0,  0,  0} ;
      BACKCOLOR {255,255,255}

da ese error.

La tabla planes es una tabla de 4 registros
planes->plan es N,2
planes->nombre es C,40
Hay otros campos que no interesan para el combo

**Comment by fyurisich** [comment]
Agrego información sobre el error enviada por correo la lista oohg@googlegroups.com

Hola..
tenía una opción funcionando que hacía mucho no ejecutaba, y ahora zas... problemas con un combo.
Antes de hacer una demo para mostrar el error, quizás se den cuenta, porque sé que se han hecho algunos cambios en los combos.. Actualicé recién oohg y me pasa, lo mismo que con el oohg del 6/2/20, pero estoy segura que en nov/diciembre esto me funcionaba ok...
 
Este es el combo, creado con el IDE deade hace mil años:
   @ 156, 310 COMBOBOX codplan_cmb ;
      WIDTH 150 ;
      ITEMSOURCE planes->nombre ;
      VALUE 1 ;
      VALUESOURCE planes->plan ;
      FONT 'MS Sans Serif' ;
      SIZE 9 ;
      ON GOTFOCUS { || This.BackColor:=clrBack  } ;
      ON LOSTFOCUS { || This.BackColor:=clrNormal } ;
      FONTCOLOR {  0,  0,  0} ;
      BACKCOLOR {255,255,255}

En la tabla:
planes->plan es N,2
planes->nombre es C,40
Hay otros campos que no me interesa cargar ni nada.


sigo con el ide 17.1114

al ejecutar me salta este error:

Error: COMBOBOX: The valtype of the first item is not valid. Program terminated.
from TCOMBO:VALUETYPE (513) in h_combo.prg
Called from TCOMBO:ISVALTYPEOK (527) in h_combo.prg
Called from TCOMBO:READDATA (476) in h_combo.prg
Called from TCOMBO:REFRESH (434) in h_combo.prg
Called from TCOMBO:DEFINE (265) in h_combo.prg
Called from INGVALESEFECTIVO (126) in F:\h3\Marcre\abitab\IngValeEfectivo.prg
Called from (b)MAIN (97) in F:\h3\Marcre\MainAbitab.prg
Called from (b)EVAL (0)
Called from _OOHG_EVAL_ARRAY (0)
Called from TTOOLBUTTON:DOEVENT (1930) in h_controlmisc.prg
Called from TTOOLBUTTON:DOEVENTMOUSECOORDS (1946) in h_controlmisc.prg
Called from TTOOLBAR:EVENTS_COMMAND (310) in h_toolbar.prg
Called from TWINDOW:EVENTS (0) in h_windows.prg
Called from _OOHG_TFORM_EVENTS2 (1813) in h_form.prg
Called from TFORMMAIN:EVENTS (0) in h_form.prg
Called from _OOHG_DOMESSAGELOOP (0)
Called from TFORMMAIN:MESSAGELOOP (647) in h_form.prg
Called from _ACTIVATEWINDOW (2868) in h_form.prg
Called from MAIN (95) in F:\h3\Marcre\MainAbitab.prg

Alguna idea??
Mil gracias
SALudos

**Comment by fyurisich** [comment]
No fue posible reproducir el error al utilizar este ejemplo:

[test.txt](https://github.com/oohg/core/files/4450841/test.txt)

Se aconseja descargar los fuentes y reconstruir las librerías de OOHG.
