### ISSUE TITLE
Error: COMBOBOX: The valtype of the first item is not valid. Program terminated - Ejemplo

### ISSUE THREAD

**Issue by pbruccoleri** [oohg/core#206]
Adjunto un ejemplo donde sí da el error, y con la librería oohg actualizada ayer de tarde (07/04/20)
Con tu test.prg no me da, pero de la forma que yo llamo a una ventana y cómo está definida, sí.

Ver #205 
[test2.zip](https://github.com/oohg/core/files/4451187/test2.zip)

**Comment by fyurisich** [comment]
Error:
COMBOBOX: The valtype of the first item is not valid.
Call stack:
Called from TCOMBO:VALUETYPE (513) in h_combo.prg
Called from TCOMBO:ISVALTYPEOK (527) in h_combo.prg
Called from TCOMBO:READDATA (476) in h_combo.prg
Called from TCOMBO:REFRESH (434) in h_combo.prg
Called from TCOMBO:DEFINE (265) in h_combo.prg

**Comment by fyurisich** [comment]
El error está causado por la cláusula VALUESOURCE {1,2}
Debe indicarse VALUESOURCE ( {1,2} ) dado que el comando en i_combobox.ch utiliza un maker the tipo "Smart stringify". Ver [https://harbour.github.io/ng/c53g01c/ng122d3c.html](url)
