### ISSUE TITLE
Combobox: Error BASE/1068  Argument error: array access

### ISSUE THREAD

**Issue by pbruccoleri** [oohg/core#207]
[test2.zip](https://github.com/oohg/core/files/4481951/test2.zip)

Con el cambio sugerido en el VALUESOURCE, de poner paréntesis, en este combo:

@ 19,97 COMBOBOX moneda_cmb ; 
ITEMS  {'Pesos','Dolares'}  ;
VALUE 1 ;
VALUESOURCE ({'P','D'})  ;
WIDTH  120 ;
FONT 'MS Sans Serif' ;
SIZE  9 ;
ON CHANGE AbrirArchivos(aAreas) ;
ON LOSTFOCUS AbrirArchivos(aAreas) ;

en el programa, al querer obtener lo que devuelve este combo de esta forma:
cMon:= {'P','D'}[frmCalculoCtas1.moneda_cmb.Value]
salta  en esa línea:
Error: Error BASE/1068  Error de argumento: acceso al array

Para que aparezca el error hay que hacer clic en el botón CALCULAR

Se suponía que me devolvía 1 o 2, por tanto para tener P o D según sea el caso tenía que hacer eso.

Ahora frmCalculoCtas1.moneda_cmb.Value devuelve un valtype= C y con ningún valor

**Comment by fyurisich** [comment]
El value de este combo es "P" si el usuario elige la primera opción de la lista desplegable o "D" si elige la segunda. La cláusula VALUESOURCE indica cual es la fuente del VALUE. En el caso del combo codplan_cmb la VALUESOURCE es el valor de un campo de una dbf, y los value que retorna son 1,2 y 5.
