### ISSUE TITLE
RICHEDITBOX raro en última actualización

### ISSUE THREAD

**Issue by nonovaz** [oohg/core#208]
Sin modificar el código, desde la última actualización, al modificar un RICHEDITBOX lo hace (sólo lo que añado) con ditinto tipo de letra.

**Screenshots**
![image](https://user-images.githubusercontent.com/33043954/82222352-7094ec80-9921-11ea-9991-481de75edd19.png)

**Error logs**
No hay error

Lo defino de esta manera
   @ 142, 100 RICHEDITBOX r_mercanci ;
      WIDTH 500 ;
      HEIGHT 60 ;
      DISABLED  ;
      ON GOTFOCUS ChangeColor(.T.) ON LOSTFOCUS ChangeColor(.F.)

En la versión anterior no daba pegas. Tengo compilaciones antiguas donde se puede ver ycon el mismo PRG sin modificar.

![error](https://user-images.githubusercontent.com/33043954/82222630-d6817400-9921-11ea-9f95-89c428b3ab24.jpg)

**Comment by fyurisich** [comment]
Por favor agrega un programa compilable con el cual hacer pruebas.
Gracias

**Comment by fyurisich** [comment]
Se cierra por falta de información suficiente para reproducir el error.
