### ISSUE TITLE
HbPrinter: Comportamiento extraño

### ISSUE THREAD

**Issue by Sercaste2019** [oohg/core#212]
Con la ultima actualización de ooHG, al imprimir en una impresora con la propiedad SET PREVIEW OFF, muestra siempre 2 carteles en secuencia antes de la impresión. No da ningún error y la impresión sale correcta pero lo veo molesto y además obliga al usuario a presionar sobre ellos.
 
Los carteles son los siguientes:
Primero este...
![imagen](https://user-images.githubusercontent.com/48957924/84387822-f9721180-abc9-11ea-808e-8ac1c3601071.png)

luego este...
![imagen](https://user-images.githubusercontent.com/48957924/84387846-03941000-abca-11ea-8c00-e90665e4ee17.png)

Haciendo mas pruebas veo que aparecen los mismos carteles si mando a imprimir a CUALQUIER impresora y con SET PREVIEW OFF
 
Haciendo una prueba con el ejemplo de la wiki https://github.com/oohg/samples/blob/master/printing/s006.prg y cambiando la linea SET PREVIEW ON por SET PREVIEW OFF, tambien salen los carteles!!!
 
Viendo los otros ejemplos de la wiki, veo que las sintaxis objeto HbPrinter, el metodo EndDoc() tiene 3 parametros!!!
¿¿¿ Como agrego esos tres parámetros utilizando la sintaxis del ejemplo s006.prg ???
 
Creo que debería estar predeterminado que NO MUESTRE ESOS CARTELES cuando decido utilizar Set Preview OFF
 
Saludos,
Sergio
 
[NewHBPrinter.zip](https://github.com/oohg/core/files/4764891/NewHBPrinter.zip)

**Comment by fyurisich** [comment]
Fixed, see ce011cdcdc433848a9eb0cc3933b2d18667461e8

**Comment by fyurisich** [comment]
El comando END DOC tiene la forma
END DOC [ WAIT | NOWAIT ] [ SIZE | NOSIZE ] [ PARENT]
