### ISSUE TITLE
Al compilar con QPM 05.05.0012 da error

### ISSUE THREAD

**Issue by Sercaste2019** [oohg/core#213]
cuando tenes un control Checkbox en un FMG con este formato:

    DEFINE CHECKBOX Check_3
        ROW    80
        COL    40
        WIDTH  170
        HEIGHT 28
        CAPTION "Generar Planilla TXT"
        VALUE .F.
        FONTNAME "Arial"
        FONTSIZE 11
        TOOLTIP ""
        ONCHANGE Veriche()
        ONGOTFOCUS (this.backcolor:={255,255,0},this.fontcolor:={0,0,0})
        ONLOSTFOCUS (this.backcolor:={0,128,255},this.fontcolor:={255,255,255})
        FONTBOLD .T.
        FONTITALIC .F.
        FONTUNDERLINE .F.
        FONTSTRIKEOUT .F.
        BACKCOLOR {0,128,255}
        FONTCOLOR {255,255,255}
        HELPID Nil
        TABSTOP .T.
        VISIBLE .T.
        TRANSPARENT .F.
        themed .t.
    END CHECKBOX

Genera un error en el  metodo "THEMED .T."

Con la version anterior no daba error !!
Saludos,
Sergio

**Comment by fyurisich** [comment]
Sergio: como puede ver en esta entrada del ChangeLog.txt, en 2016 se hizo un cambio.
Saludos
Fernando

2016-12-16 22:42 UTC-0300 Fernando Yurisich <fyurisich@oohg.org>
  * include\i_altsyntax.ch
  * include\i_button.ch
  * include\i_checkbox.ch
  * include\i_radiogroup.ch
    * INCOMPATIBLE.
      THEMED and NOTHEME clauses changed by OOHGDRAW and WINDRAW.
      OOHGDRAW is the default clause unless the OS does not supports
      visual styles or if visual styles are disabled for the app, in
      which case defaults to WINDRAW.
      Those who do not want to change their sources must include
      this pre-processor directives:
      #xtranslate BUTTON [ <x> ] THEMED => BUTTON [ <x> ] OOHGDRAW
      #xtranslate BUTTON [ <x> ] NOTHEME => BUTTON [ <x> ] WINDRAW
      #xtranslate CHECKBUTTON [ <x> ] THEMED => BUTTON [ <x> ] OOHGDRAW
      #xtranslate CHECKBUTTON [ <x> ] NOTHEME => BUTTON [ <x> ] WINDRAW
      #xtranslate CHECKBOX [ <x> ] THEMED => CHECKBOX [ <x> ] OOHGDRAW
      #xtranslate CHECKBOX [ <x> ] NOTHEME => CHECKBOX [ <x> ] WINDRAW
      #xtranslate RADIOGROUP [ <x> ] THEMED => RADIOGROUP [ <x> ] OOHGDRAW
      #xtranslate RADIOGROUP [ <x> ] NOTHEME => RADIOGROUP [ <x> ] WINDRAW
      #translate THEMED <themed> => OOHGDRAW <themed>
      #translate NOTHEME <notheme> => WINDRAW <notheme>
