### ISSUE TITLE
HbPrinter: Comportamiento extraño

### ISSUE THREAD

**Issue by Sercaste2019** [oohg/core#216]
Hola Fernando,

Disculpa si te molesto...pero quizas para mi es importante "entender" el comportamiento de HbPrinter...

Haciendo pruebas con tus ultimos cambios, veo que si utilizo el parametro END DOC NOWAIT (Ya que no quiero que aparezca NINGUN cartel durante el proceso/impresion) utilizando **vista previa**, la misma aparece un instante y luego desaparece, y tampoco imprime.
Te adjunto el ejemplo s006.prg de gitub para que veas el comportamiento.

En mi opinion y por comportamiento, utilizando solo END DOC, no deberia mostrar nunca un cartel (tal cual las versiones anteriores). 
En mi caso uso mucha impresión, generaciones a impresoras predeterminadas, seleccionadas, vistas previas y sin vistas previas, salidas a PDF (por ejemplo usando Bullzip PDF, ya sea a un archivo directo a traves de su API, o simplemente usando su impresora generada)....incluso a mas de un tamaño de hoja, etc....y para ello uso una rutina global, que recibe muchos parametros.
Ademas no comprendo exactamente que hace cada parametro de END DOC, por ejempo SIZE o PARENT...
Desde ya agradesco tus observaciones...
Abrazos,
Sergio

#include "oohg.ch"
#include "winprint.ch"

PROCEDURE Main

   PUBLIC hbprn

   SET AUTOADJUST ON

   DEFINE WINDOW Win_1 ;
      AT 0, 0 ;
      WIDTH 400 ;
      HEIGHT 400 ;
      TITLE 'OOHG - HBPRINTER Demo' ;
      ICON 'ZZZ_PRINTICON' ;
      MAIN

      DEFINE MAIN MENU
         MENUITEM 'Test Default' ACTION Demo( 1 )
         MENUITEM 'Test Dialog'  ACTION Demo( 2 )
         MENUITEM 'Exit'         ACTION ThisWindow.Release
      END MENU

      @ 50, 20 CHECKBOX chk_Preview ;
         CAPTION "Preview" ;
         VALUE .T.

      ON KEY ESCAPE ACTION ThisWindow.Release
   END WINDOW

   CENTER WINDOW Win_1
   ACTIVATE WINDOW Win_1

   QUIT

   RETURN

PROCEDURE Demo( nOption )

   a10colors := { YELLOW, PINK, RED, FUCHSIA, BROWN, ORANGE, GREEN, PURPLE, BLACK, BLUE }

   aColor := Array( 200 )
   FOR i := 0 TO 19
      FOR j := 1 TO 10
         aColor[ i * 10 + j ] := a10colors[ j ]
      NEXT j
   NEXT i

   INIT PRINTSYS FOLDER hb_DirBase()   // Initialize HBPrinter system

   IF nOption == 2
      SELECT BY DIALOG                 // Let the user select a printer via dialog
   ELSE
      SELECT DEFAULT                   // Select the default printer
   ENDIF

   IF HBPRNERROR != 0                  // Test error code
      MsgStop( 'Print cancelled!' )
      RETURN
   ENDIF

   /*
    * The best way to get the most similiar printout on various printers
    * is to use SET UNITS MM and set margins large enough for all of them.
    */
   SET UNITS MM                        // Set @... units to milimeters

   SET PAPERSIZE DMPAPER_A4            // Set paper's size to A4

   SET ORIENTATION PORTRAIT            // Set paper's orientation to portrait

   SET BIN DMBIN_FIRST                 // Set paper's origin to the first bin

   SET QUALITY DMRES_HIGH              // Set printer's quality to high

   SET COLORMODE DMCOLOR_COLOR         // Set printer's color mode to color

   SET COPIES TO 2                     // Set printer's number of copies

   IF Win_1.chk_Preview.Value
      SET PREVIEW ON                      // Enable preview
   ELSE
      SET PREVIEW OFF                      // Disable preview
   ENDIF

   SET PREVIEW RECT MAXIMIZED          // Maximize the preview window

   ENABLE THUMBNAILS                   // Show page thumbnails

   DEFINE FONT "TitleFont" ;           // Creates a font to use with @...SAY command
      NAME "Courier New" ;
      SIZE 24 ;
      BOLD

   START DOC                           // Initialize the print job

      FOR i := 1 TO Len( aColor )

         START PAGE                    // Create a page

            @ 20,20,50,190 RECTANGLE

            @ 25,25 PICTURE "ZZZ_AAAOOHG" ;
               SIZE 20,15

            @ 35,60 SAY "HBPrinter Demo" ;
               FONT "TitleFont" ;
               COLOR RED ;
               TO PRINT

            @ 140,60 SAY "Page Number: " + LTrim( Str( i ) ) ;
               FONT "TitleFont" ;
               COLOR aColor[ i ] ;
               TO PRINT

            @ 270,20,270,190 LINE

         END PAGE

      NEXT

   END DOC NOWAIT
*   END DOC SIZE

   RELEASE PRINTSYS                    // Release HBPrinter system

   RETURN

**Comment by fyurisich** [comment]
NOWAIT no tiene nada que ver con carteles.
Esta cláusula hace que la ventana de la preview no sea modal y por lo tanto permita tener 2 listados en pantalla a la vez. Mira el ejemplo printing\s002.prg

**Comment by fyurisich** [comment]
SIZE permite que se pueda modificar el tamaño de la ventana de la preview.
Esto permite ver 2 listados en pantalla a la vez sin que uno tape al otro.

**Comment by fyurisich** [comment]
PARENT permite que la ventana de la preview se hija de otra ventana en la aplicación, de forma que si la ventana padre se cierra también lo haga la hija.

**Comment by fyurisich** [comment]
Por favor adjunta los .prg en lugar de copiarlos directamente, es más práctico.

**Comment by fyurisich** [comment]
Si miras como quedó al subirlo verás que GitHub cambia los * por una bullet.
Para mi no es tan solo copiar y pegar sino que tengo fijarme en cosas como estás para poder compilar.

**Comment by fyurisich** [comment]
El ejemplo que adjuntas no es válido en el caso de que PREVIEW esté en ON.
El END DOC muestra la ventana de la PREVIEW.
Dado que se agregó ENDDOC, la ventana de preview no es modal, por lo que la ejecución no se detiene.
Al volver el control a tu rutina se ejecuta RELEASE PRINTSYS, con lo cual se cierra la ventana de la preview.
Esto es lo que hace que se vea apenas un momento.
En definitiva, el comportamiento que observas es el esperado.

**Comment by Sercaste2019** [comment]
¿Por que dices que no es valido?
Yo lo ejecuto y funciona BIEN con el preview ON. Precisamente cuando el Preview es OFF es que muestra un cartel. Ese comportamiento ANTES no era asi, y es precisamente lo que estoy queriendo decir. 
Mi unica intención, es que no aparezca ningun cartel que interrumpa el flujo si decido un preview OFF y END DOC (como fue siempre que funcionó HBPrinter).

Quizas la cuestion esta en el valor por default cuando se usa END DOC sin nada mas...

¿Se entiendo lo que quiero decir?

**Comment by fyurisich** [comment]
Si quieres que se comporte como antes, quita el NOWAIT, ya que antes NOWAIT no existía.
¿Por qué quieres agregar NOWAIT y que se siga comportando como antes?

**Comment by fyurisich** [comment]
¿Probaste el END DOC sin nada más para ver como se comporta?

**Comment by Sercaste2019** [comment]
Fernando, 
En el ejemplo que te puse (sacado del s006.prg) fijate el END DOC esta sin nada
No agrego el NOWAIT !!!

Te adjnto PRG,EXE y QPM para que veas que no agrego nada!!!!....SOLO quiero generar la impresion sin PREVIEW y que no aparesca ningun cartel
[HBPrinter.zip](https://github.com/oohg/core/files/4775242/HBPrinter.zip)

**Comment by fyurisich** [comment]
La única explicación que se me ocurre al mensaje que muestra tu programa es que no has actualizado correctamente la librería con los cambios de GitHub. Si yo compilo el ejemplo con la librería actualizada este mensaje no sale.

**Comment by Sercaste2019** [comment]
Fernando, con tu última observación, me di cuenta de algo: no alcanza con "copiar" las LIBS recreadas al arbol de ooHG que uso oficialmente para los sistemas!!!!...Tambien debo copiar la carpeta INCLUDE!!!!...
Mala mía!!!...se me paso esto en el proceso de migracion...
Disculpa mi olvido, disculpa el tiempo que te hize perder!!!
ABRAZOS TOTALES

**Comment by fyurisich** [comment]
No hay problema, me alegra que lo hayas podido solucionar.
