### ISSUE TITLE
ToolBar superior de HBPrinter NO APARECE...en Win XP

### ISSUE THREAD

**Issue by Sercaste2019** [oohg/core#261]
Hola Fernando,

He descubierto que el menu superior o ToolBar de HBPrinter con preview, NO APARECE en Windows XP.
Te adjunto el ejemplo. Probalo en un Windows XP y verás que el ToolBar no aparece y por lo tanto no se puede hacer mas nada con la impresión.

Con un toolbar en mi programa (dentro de un SPLITBOX) tampoco aparece. Veré de hacer un pequeño ejemplo.

Saludos y gracias,
Sergio
[ToolBar.zip](https://github.com/oohg/core/files/4789410/ToolBar.zip)

**Comment by fyurisich** [comment]
Sergio, no tengo acceso a ningún XP para probar. Supongo que algunas de las mejoras hechas a XP en los últimos tiempos afectó a la toolbar. Pero teniendo en cuenta que el soporte para XP terminó hace mucho tiempo pienso que no vale la pena arreglarlo. Saludos. Fernando
