### ISSUE TITLE
h_error.prg no respeta el seteo de lenguaje

### ISSUE THREAD

**Issue by sharley1** [oohg/core#290]
El seteo de los mensajes de error en h_error.prg (método NEW) ignora el seteo de lenguaje realizado en la aplicación.
La solución utilizada para resolver esta situación fué reemplazar el código:

IF ! ValType( cLang ) $ "CM" .OR. Empty( cLang )          
   cLang   := _OOHG_GetLanguage()                         
ENDIF                                                     

por

IF ! ValType( cLang ) $ "CM" .OR. Empty( cLang )          
   cLang   := _OOHG_GetLanguage()                         
   ::cLang := cLang                                       
ENDIF

**Comment by fyurisich** [comment]
Ver 4719fcbdb65dec5502c43a3eb940dae4146fd853
