### ISSUE TITLE
TPRINT: Class MiniPrint fills all rectangles with color black

### ISSUE THREAD

**Issue by wfedeli** [oohg/core#296]
Hola,
Hice la actualización de OOHG a la versión del 18.07.2020.
Utilizo para imprimir tprint("MINIPRINT") y comenzó a imprimir en la sentencia oprint:printroundrectangle y oprint:printectangle el rectángulo todo en negro
En en ejemplo está hecho la misma impresion con MiniPrint y HBPRINTER y con este finciona bien
Probé agregarle los nuevos parámetros del color, pero sigue imprimiendo el rectángulo negro.

[MiniPrint.zip](https://github.com/oohg/core/files/5046498/MiniPrint.zip)

**Comment by fyurisich** [comment]
Fixed. See a6e5c83a32f4bb49e62a728d2df169d3e9a575a3
