### ISSUE TITLE
Regenerar Lib

### ISSUE THREAD

**Issue by wfedeli** [oohg/core#319]
Hola 
Baje el core-master con el arreglo de  [oohg/core] TPRINT: Class MiniPrint fills all rectangles with color black (#296)
y al regenerar las lib con;

makelib32.bat

se detiene con el siguiente error

Harbour 3.2.0dev (r1708131853)
Copyright (c) 1999-2016, http://harbour-project.org/
Compiling 'h_label.prg'...
h_label.prg(99) Error E0030  Syntax error "syntax error at 'UCURSOR'"
h_label.prg(139) Warning W0001  Ambiguous reference 'UCURSOR'
h_label.prg(148) Warning W0001  Ambiguous reference 'BONMOVE'
h_label.prg(148) Warning W0001  Ambiguous reference 'BONMOVE'
h_label.prg(149) Warning W0001  Ambiguous reference 'BONLEAVE'
h_label.prg(149) Warning W0001  Ambiguous reference 'BONLEAVE'
1 error

No code generated.

Muchas gracias

Walter Fedeli

**Comment by fyurisich** [comment]
Fixed. See a13ae96ae87c0706edcb2449469842762bfde5f7
