### ISSUE TITLE
Error en Grid con ON ENTER

### ISSUE THREAD

**Issue by ViCagCan** [oohg/core#565]
Buenas tardes:

He utilizado un ejemplo de ooHG  quitando lo que no es necesario para ver el error y añadiendo las dos líneas ON ENTER y ON DBLCLICK para que muestre la información deseada.

Lo que aquí se quiere hacer es que se pueda ir uno moviendo por el contenido del GRID y en un momento dado ya sea con ENTER o DBLCLICK nos muestre el valor/contenido de la línea en la cual nos encontramos,

Si nos movemos por el Grid y pulsamos DBLCLICK la acción definida muestra el valor que tiene dicha línea pero si pulsamos Enter... no aparece nada.

He creado de nuevo las lib con los archivos más reciente que hay y el problema persiste.

Si por el contrario en el ON ENTER se le indica que realice cualquier otra acción... no parece dar problema.

Un saludo.

[ErrorGrid.zip](https://github.com/oohg/core/files/9608883/ErrorGrid.zip)

**Comment by fyurisich** [comment]
No es un error en la librería.
Esa funcionalidad nunca se implementó y por eso el ON ENTER no recibe el
valor THIS.CellValue.
Ayer subí una mejora a GitHub implementando lo anterior (ver #563).

Saludos
Fernando Yurisich
If you like my work, please consider supporting me with a donation via
PayPal
<https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=VYXQYCKWXLWAG&lc=UY&item_name=FYM&item_number=OOHG%2fQPM&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted>
or
Amazon Gift Card <https://www.amazon.com/gift-cards/>.
