### ISSUE TITLE
Same compile error

### ISSUE THREAD

**Issue by nikko1960** [oohg/core#98]
Hi Fernando, probably I have some configuration issues, so this is my environment
Windows 10 pro 32
harbour 3.2 last commit
OOHG last commit
mingw 8.1
these are my environment variables

-----------------------------------------------------------
HB_PATH=C:\OOHG\HB_32
HG_CCOMP=C:\mingw-8.1.0-win32\mingw32
HG_HRB=C:\OOHG\HB_32
HG_MINGW=C:\mingw-8.1.0-win32\mingw32
HG_ROOT=C:\OOHG
-----------------------------------------------------------
HOMEDRIVE=C:
HOMEPATH=\Users\atc
-----------------------------------------------------------
LIB_GUI=lib\hb\mingw
LIB_HRB=lib\win\mingw
-----------------------------------------------------------
Path=C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS\system32\wbem;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\mingw-8.1.0-win32\mingw32\bin;C:\OOHG\hb_32\bin\win\mingw;C:\OOHG;

when i try to build HM32

i receive  the same message when i run build whithout (HM32) parameter

so i run hbmk2 mgide.hbp

even if i have these warnings 
C:/mingw-8.1.0-win32/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/bin/ld.exe: .rsrc merge failure: duplicate leaf: type: 3 (ICON) name: 7 lang: 409
C:/mingw-8.1.0-win32/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/bin/ld.exe: .rsrc merge failure: duplicate leaf: type: 3 (ICON) name: 6 lang: 409
C:/mingw-8.1.0-win32/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/bin/ld.exe: .rsrc merge failure: duplicate leaf: type: 3 (ICON) name: 5 lang: 409
C:/mingw-8.1.0-win32/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/bin/ld.exe: .rsrc merge failure: duplicate leaf: type: 3 (ICON) name: 4 lang: 409
C:/mingw-8.1.0-win32/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/bin/ld.exe: .rsrc merge failure: duplicate leaf: type: 3 (ICON) name: 3 lang: 409
C:/mingw-8.1.0-win32/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/bin/ld.exe: .rsrc merge failure: duplicate leaf: type: 3 (ICON) name: 2 lang: 409
C:/mingw-8.1.0-win32/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/bin/ld.exe: .rsrc merge failure: duplicate leaf: type: 3 (ICON) name: 1 lang: 409

oide works

the preferences are these

1 tab Project
xBase compiler = Harbour
C compiler = Mingw
Build type = Compile.bat
2 tab (x)Harbour
Harbour-Mingw = C:\OOHG\hb_32\bin\win\mingw
3 tab C Compiler
Mingw Folder = C:\mingw-8.1.0-win32\mingw32\bin
4 Tab GUI
ooHG-Hb-Mingw = C:\OOHG\lib\hb\mingw

but when i try to compile from oide a project i receive these message
File is missing: "program.exe" ( where program is the name of first prg
when i change from Compile.bat to own make the result is the same :

I have not looked the source of ide and to be sincerously i found your .bat files a little
difficult to manipulate to find the way to solve the problem

The simple way for me is  using hbmk2 + hbp project, is simple to do, to play, to run.
but this is my thought

regards Domenico

regards

**Comment by fyurisich** [comment]
I've just uploaded a fix for ide\build.bat and fmt\build.bat. See 8003bcd
​The warnings mean that you are linking the same resource file twice.
To configure the IDE properly you must set de fields with the same paths used for the env vars.
  Harbour-Mingw = C:\OOHG\hb_32\bin\win\mingw
  Mingw Folder = C:\mingw-8.1.0-win32\mingw32
  ooHG-Hb-Mingw = C:\OOHG

Regards
Fernando

**Comment by fyurisich** [comment]
In order to use IDE's compile option you must delete compile30.bat and compile34.bat so compile32.bat is detected and used automatically.

**Comment by nikko1960** [comment]
Hi Fernando, thank for your replay

first i changed something in my configuration to simplify the path of
harbour, becouse i want to use not only with your GUI.

now harbour is in this directory c:\hb_32

this as you know, is gitted from github, so the path is builded by Harbour
chiefs ( as you are the OOHG Chief )

i have changed the environment settings and setted the sames in oide 19.0228

running with ownmake, becouse compile.bat give me another error

this is the error

C:\hb_32\bin\win\mingw\BIN\HARBOUR.EXE D:\finanz\PAGODIL.prg -n -q
-iD:\finanz -iC:\hb_32\bin\win\mingw\INCLUDE -iC:\OOHG\INCLUDE
-oD:\finanz\OBJ\PAGODIL.c
process_begin: CreateProcess(NULL, C:\hb_32\bin\win\mingw\BIN\HARBOUR.EXE
D:\finanz\PAGODIL.prg -n -q -iD:\finanz -iC:\hb_32\bin\win\mingw\INCLUDE
-iC:\OOHG\INCLUDE -oD:\finanz\OBJ\PAGODIL.c, ...) failed.
make (e=2): Impossibile trovare il file specificato.

mingw32-make: *** [makefile.gcc:28: D:\finanz\OBJ\PAGODIL.c] Error 2

as you see ownmake , make an error, becouse try to find harbour.exe in a
directory that does not exist

C:\hb_32\bin\win\mingw\BIN\
the correct directory is
C:\hb_32\bin\win\mingw\

the second error is this, a directory that does not exist
-iC:\hb_32\bin\win\mingw\INCLUDE
the correct directory is
-iC:\hb_32\INCLUDE

and these are not my mistakes

To solve the problem i suggest to read environment variables correct
setted for example
SET OOHG_MINGW_BIN=
SET OOHG_HARBOUR_BIN=
SET OOHG_HARBOUR_INCLUDE=
SET OOHG_HARBOUR_LIB=

or setting these PATHS in OIDE preferences

or If i can suggest you,  put another buildtype option
hbmk2
we the programmers build a program.hbp to build it whithout any other effort

these are my opinion

the last one is the less effort programming patch you can make whithout
loose more time

regards

Domenico

P.S. si quieres que escriba en espanol enformame
saludos desde italia















Il giorno dom 3 mar 2019 alle ore 22:49 Fernando Yurisich <
notifications@github.com> ha scritto:

**Comment by fyurisich** [comment]
Hi, Domenico: 
I've just uploaded some changes to the IDE that allow fully customization of Harbour, MinGW and OOHG subfolders. I'm currently working on the new build type that you suggested. 
Regards
